(()=>{"use strict";
const DEFAULT_WORKER="";
const $=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const role=(new URLSearchParams(location.search).get("role")||"lizzy").toLowerCase()==="hq"?"hq":"lizzy";document.getElementById("app").dataset.role=role;
const ROOM={reception:"Reception",staff_offices:"Staff Offices",security_room:"Security Room",deposit_room:"Deposit Room",main_vault:"Main Vault",loading_bay:"Loading Bay",garage:"Garage"};
const ROOM_DESC={reception:"Polished marble, a visitor desk, and several employees who have no idea this is about to become their problem.",staff_offices:"Unlocked terminals, hanging coats and exactly the kind of access card a responsible bank would not leave unattended.",security_room:"Blue CCTV monitors, alarm controls and a terminal that could make Mikael's afternoon substantially worse.",deposit_room:"Rows of deposit boxes, small valuables and enough suspicious paperwork to hide a clue in.",main_vault:"The serious money. Brass mechanisms, red warning lights and the President's completely unnecessary valuables.",loading_bay:"Industrial doors, vehicle access and a side exit that can become an escape route if prepared.",garage:"Concrete, engines and freedom. If HQ has not guessed correctly."};
const ROOM_IMG={reception:"reception.webp",staff_offices:"staff.webp",security_room:"security.webp",deposit_room:"deposits.webp",main_vault:"vault.webp",loading_bay:"loading.webp",garage:"garage.webp"};
const ITEMS={camera_loop:["📹","Camera Loop","Make one camera appear empty for 15s."],noise_maker:["🔊","Noise Maker","Create a suspicious sound in any room."],fake_visitor_pass:["🪪","Fake Visitor Pass","Pass the initial Staff Offices access check automatically."],door_jammer:["🚪","Door Jammer","Add 5 seconds to an active guard search warning."],decoy_bag:["💼","Decoy Bag","Create a fake stolen-loot signal elsewhere."]};
const POS={reception:[8,13],staff_offices:[37,8],security_room:[70,8],deposit_room:[10,54],main_vault:[42,48],loading_bay:[72,50],garage:[72,78]};
let state=null,serverOffset=0,busy=false,loadout=new Set(),lastEndRun=null,worker=localStorage.getItem("bankHeistWorkerUrl")||localStorage.getItem(role==="hq"?"mickyhq_test_worker_url_v1":"lizzyos_test_worker_url_v1")||"",hqKey=localStorage.getItem("bankHeistHqKey")||"";
function parentValue(id){try{return window.parent!==window?window.parent.document.getElementById(id)?.value?.trim()||"":""}catch{return""}}
function getWorker(){return localStorage.getItem("bankHeistWorkerUrl")||localStorage.getItem(role==="hq"?"mickyhq_test_worker_url_v1":"lizzyos_test_worker_url_v1")||localStorage.getItem("mickyhq_test_worker_url_v1")||localStorage.getItem("lizzyos_test_worker_url_v1")||parentValue("testWorkerUrl")||window.TEST_WORKER_URL||""}
function getKey(){return localStorage.getItem("bankHeistHqKey")||parentValue("hqKey")||hqKey||""}
function rid(){return crypto.randomUUID?crypto.randomUUID():`r_${Date.now()}_${Math.random().toString(36).slice(2)}`}
async function api(action,payload={}){const w=getWorker();if(!w)throw new Error("No TEST Worker URL found. Set the TEST Worker URL first.");const body={action,...payload,requestId:payload.requestId||rid()};if(role==="hq"||payload.role==="hq")body.hqKey=getKey();const r=await fetch(w,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store"});const d=await r.json().catch(()=>({success:false,error:"Invalid Worker response"}));if(!r.ok||d.success===false){if(d.state)accept(d.state);throw new Error(d.error||`Request failed (${r.status})`)}return d}
async function refresh(){if(busy||document.hidden)return;try{const d=await api("bank_heist_state",{role});accept(d)}catch(e){setStatus(e.message)}}
function accept(d){state=d;serverOffset=Number(d.serverNow||Date.now())-Date.now();render()}
function now(){return Date.now()+serverOffset}
function fmt(ms){const s=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function setStatus(t){if(state?.phase==="lobby")$("lobbyStatus").textContent=t;else (role==="hq"?$("hqResult"):$("fieldResult")).textContent=t}
async function act(action,payload={}){if(busy)return;busy=true;try{accept(await api(action,payload))}catch(e){setStatus(e.message)}finally{busy=false}}
function render(){if(!state)return;$("rolePill").textContent=role==="hq"?"MIKAEL // HQ":"LIZZY // FIELD";const lobby=state.phase==="lobby";$("lobby").classList.toggle("hidden",!lobby);$("game").classList.toggle("hidden",lobby);if(lobby)renderLobby();else{if(role==="hq")renderHQ();else renderLizzy();renderComms();renderEnd();}tick()}
function renderLobby(){
  if(role==="lizzy"){
    $("lobbyTitle").textContent="Lizzy, choose your heist kit.";$("lobbyText").textContent="Pick exactly three items. Mikael only sees whether you are ready — your actual loadout stays hidden.";$("loadoutGrid").classList.remove("hidden");$("readyBtn").classList.remove("hidden");$("startBtn").classList.add("hidden");$("resetBtn").classList.add("hidden");
    if(!loadout.size&&Array.isArray(state.loadout))state.loadout.forEach(x=>loadout.add(x));
    $("loadoutGrid").innerHTML=Object.entries(ITEMS).map(([id,[em,n,d]])=>`<button class="loadout ${loadout.has(id)?"on":""}" data-loadout="${id}"><span class="emoji">${em}</span><strong>${n}</strong><small>${d}</small></button>`).join("");qa("[data-loadout]").forEach(b=>b.onclick=()=>{const id=b.dataset.loadout;if(loadout.has(id))loadout.delete(id);else if(loadout.size<3)loadout.add(id);renderLobby()});$("readyBtn").disabled=loadout.size!==3;$("readyBtn").textContent=state.lizzyReady?"READY — UPDATE LOADOUT":"LOCK LOADOUT & READY UP";$("lobbyStatus").textContent=state.lizzyReady?"Ready. Waiting for Mikael to start the heist.":`${loadout.size}/3 items selected.`;
  }else{
    $("lobbyTitle").textContent="President Mikael: security is standing by.";$("lobbyText").textContent="Lizzy's equipment choices are hidden. Once she is ready, start the 15-minute heist.";$("loadoutGrid").classList.add("hidden");$("readyBtn").classList.add("hidden");$("startBtn").classList.remove("hidden");$("resetBtn").classList.remove("hidden");$("startBtn").disabled=!state.lizzyReady;$("lobbyStatus").textContent=state.lizzyReady?"✅ Lizzy is ready. Her actual equipment remains classified.":"⏳ Waiting for Lizzy to lock her loadout.";
  }
}
$("readyBtn").onclick=()=>act("bank_heist_lizzy_loadout",{items:[...loadout],ready:true});$("startBtn").onclick=()=>act("bank_heist_start");$("resetBtn").onclick=()=>{if(confirm("Reset the entire test heist?"))act("bank_heist_reset")};
function interactionButtons(){const f=state.found||{},r=state.room,b=[];const add=(id,label,disabled=false)=>b.push(`<button data-int="${id}" ${disabled?"disabled":""}>${label}</button>`);
 if(r==="reception"){add("visitor_pass","🪪 Obtain visitor pass",!!f.visitorPass);add("distract","🎭 Distract receptionist")}
 if(r==="staff_offices"){add("take_card","💳 Take staff access card",!!f.accessCard);add("computer","💻 Search logged-in computer",!!f.clue2)}
 if(r==="security_room"){add("security_terminal","🖥 Search security terminal",!!f.clue4);add("disable_cameras","📵 Disrupt cameras (14s)")}
 if(r==="deposit_room"){add("deposit_clue","📒 Search deposit ledger",!!f.clue3);add("deposit_cash","💵 Take cash tray · +MB2,500",!!f.depositCash||state.loot>=20000);add("deposit_diamonds","💎 Take small valuables · +MB3,000",!!f.depositDiamonds||state.loot>=20000)}
 if(r==="main_vault"){if(!state.vaultOpen)add("vault_code","🔐 Enter vault code");else{add("vault_cash","💰 Cash reserve · +MB8,000",!!f.vaultCash||state.loot>=20000);add("vault_stapler","📎 Diamond stapler · +MB4,000",!!f.vaultStapler||state.loot>=20000);add("vault_fund","🏛 Emergency fund · +MB5,000",!!f.vaultFund||state.loot>=20000);add("vault_gold","🪙 Ceremonial gold · +MB3,000",!!f.vaultGold||state.loot>=20000)}}
 if(r==="loading_bay"){add("prepare_getaway","🚚 Prepare loading-bay getaway",state.getawayPrepared);if(state.getawayPrepared)b.push(`<button data-escape="loading_bay">🏃 ESCAPE VIA LOADING BAY</button>`)}
 if(r==="garage")b.push(`<button data-escape="garage">🏎 ESCAPE VIA GARAGE</button>`);
 b.push(`<button data-hide="1">🫥 Hide</button>`);return b.join("")}
function renderLizzy(){$("lizzyView").classList.remove("hidden");$("hqView").classList.add("hidden");$("sceneImage").style.backgroundImage=`url("heist-assets/${ROOM_IMG[state.room]}")`;$("roomTitle").textContent=state.roomLabel||ROOM[state.room];$("roomDescription").textContent=ROOM_DESC[state.room]||"";$("loot").textContent=`MB${Number(state.loot||0).toLocaleString()}`;$("strikes").textContent=`${state.strikes} / 3`;$("fieldResult").textContent=state.lastResult||"";
 const lockedBusy=!!(state.moving||state.action);$("routes").innerHTML=(state.routes||[]).map(x=>`<button data-move="${x.to}" class="${x.locked?"routeLocked":""}" ${lockedBusy||x.locked||x.requires?"disabled":""}>${x.locked?"🔒 ":"→ "}${esc(x.label)}${x.requires?` · ${esc(x.requires)}`:""}</button>`).join("")||"<small>No route.</small>";qa("[data-move]").forEach(b=>b.onclick=()=>act("bank_heist_lizzy_move",{to:b.dataset.move}));
 $("roomActions").innerHTML=interactionButtons();qa("[data-int]").forEach(b=>b.onclick=()=>{if(b.dataset.int==="vault_code")return $("vaultDialog").showModal();act("bank_heist_lizzy_interact",{interaction:b.dataset.int})});qa("[data-hide]").forEach(b=>b.onclick=()=>act("bank_heist_lizzy_hide"));qa("[data-escape]").forEach(b=>b.onclick=()=>act("bank_heist_lizzy_escape",{exit:b.dataset.escape}));
 $("equipment").innerHTML=(state.loadout||[]).map(id=>{const [em,n,d]=ITEMS[id]||["?",id,""];const used=(state.used||[]).includes(id);return `<div class="item ${used?"used":""}"><div><strong>${em} ${n}</strong><small>${used?"USED / CONFISCATED":d}</small></div>${used||id==="fake_visitor_pass"?"":`<button data-item="${id}">USE</button>`}</div>`}).join("");qa("[data-item]").forEach(b=>b.onclick=()=>useItem(b.dataset.item));
 const f=state.found||{},cl=[];if(f.clue1||f.clue2)cl.push("Computer: first two vault digits are 7 • 3");if(f.clue3)cl.push("Deposit ledger: third vault digit is 1");if(f.clue4)cl.push("Security terminal: final vault digit is 9");if(f.accessCard)cl.push("Staff access card acquired");if(f.visitorPass)cl.push("Visitor pass acquired");$("clues").innerHTML=cl.length?cl.map(x=>`<div class="clue">${esc(x)}</div>`).join(""):`<div class="clue">No useful clues yet.</div>`;
 const danger=state.threat;$("dangerBanner").classList.toggle("hidden",!danger);if(danger)$("dangerBanner").textContent=`🚨 SECURITY SEARCH IN ${Math.ceil(danger.searchIn/1000)}s — hide, leave or use your jammer.`;const busyText=state.moving?`MOVING → ${ROOM[state.moving.to]} · ${Math.ceil(state.moving.arriveIn/1000)}s`:state.action?`ACTION IN PROGRESS · ${Math.ceil(state.action.completeIn/1000)}s`:state.hiding?"YOU ARE HIDING — doing anything else reveals you":"";$("busyBanner").classList.toggle("hidden",!busyText);$("busyBanner").innerHTML=busyText+(state.action?` <button id="cancelAction">CANCEL</button>`:"");if(state.action)$("cancelAction").onclick=()=>act("bank_heist_lizzy_cancel");qa("[data-drop]").forEach(b=>b.disabled=!state.loot);applyPayout();}
function chooseTarget(title,cb){$("targetTitle").textContent=title;$("targetButtons").innerHTML=Object.entries(ROOM).map(([id,n])=>`<button value="cancel" data-target="${id}">${n}</button>`).join("");qa("[data-target]").forEach(b=>b.onclick=()=>cb(b.dataset.target));$("targetDialog").showModal()}
function useItem(item){if(["noise_maker","decoy_bag","camera_loop"].includes(item))return chooseTarget(`Choose ${ITEMS[item][1]} target`,target=>act("bank_heist_lizzy_item",{item,target}));act("bank_heist_lizzy_item",{item})}
qa("[data-drop]").forEach(b=>b.onclick=()=>act("bank_heist_lizzy_drop",{amount:b.dataset.drop}));
$("vaultForm").onsubmit=e=>{e.preventDefault();$("vaultDialog").close();act("bank_heist_lizzy_interact",{interaction:"vault_code",code:$("vaultCode").value.trim()});$("vaultCode").value=""};
function buildSelects(){const opts=Object.entries(ROOM).map(([id,n])=>`<option value="${id}">${n}</option>`).join("");$("cameraRoom").innerHTML=opts;$("guardRoom").innerHTML=opts;const edges=[];for(const [a,ns] of Object.entries(state.map||{}))for(const b of ns)if(a<b)edges.push([a,b]);$("lockEdge").innerHTML=edges.map(([a,b])=>`<option value="${a}|${b}">${ROOM[a]} ↔ ${ROOM[b]}</option>`).join("")}
function renderMap(){const m=$("bankMap"),w=m.clientWidth||800,h=m.clientHeight||470;let html="";const locks=new Set((state.locks||[]).map(x=>x.edge));for(const [a,ns] of Object.entries(state.map||{}))for(const b of ns)if(a<b){const [x1,y1]=POS[a],[x2,y2]=POS[b],ax=x1/100*w+75,ay=y1/100*h+35,bx=x2/100*w+75,by=y2/100*h+35,dx=bx-ax,dy=by-ay,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;html+=`<div class="mapLine ${locks.has([a,b].sort().join("|"))?"locked":""}" style="left:${ax}px;top:${ay}px;width:${len}px;transform:rotate(${ang}deg)"></div>`}for(const [id,n] of Object.entries(ROOM)){const [x,y]=POS[id],guards=(state.guards||[]).filter(g=>g.room===id&&!g.target),seen=state.lastSeen?.room===id,guarded=guards.length;html+=`<div class="mapNode ${seen?"seen":""} ${guarded?"guarded":""}" style="left:${x}%;top:${y}%"><strong>${n}</strong><small>${seen?"LAST SEEN":"camera available"}</small><div>${guards.map(g=>`<span class="guardDot">${g.id}</span>`).join("")}</div></div>`}m.innerHTML=html}
function renderHQ(){$("lizzyView").classList.add("hidden");$("hqView").classList.remove("hidden");if(!$("cameraRoom").options.length)buildSelects();$("power").textContent=Math.floor(state.power);$("powerBar").style.width=`${Math.max(0,Math.min(100,state.power))}%`;$("hqResult").textContent=state.lastResult||"";$("lastSeen").textContent=state.lastSeen?`LAST SEEN: ${ROOM[state.lastSeen.room]} · ${Math.max(0,Math.floor((state.serverNow-state.lastSeen.at)/1000))}s ago`:"NO CONFIRMED SIGHTING";renderMap();
 const cd=state.cooldowns||{};$("cameraCd").textContent=cd.camera?`${Math.ceil(cd.camera/1000)}s`:"";$("lockCd").textContent=cd.lock?`${Math.ceil(cd.lock/1000)}s`:"";$("scanCd").textContent=cd.scan?`${Math.ceil(cd.scan/1000)}s`:"";$("protectCd").textContent=cd.protect?`${Math.ceil(cd.protect/1000)}s`:"";$("cameraBtn").disabled=!!cd.camera||state.securityPaused>0;$("lockBtn").disabled=!!cd.lock||state.securityPaused>0;$("scanBtn").disabled=!!cd.scan||state.securityPaused>0;$("protectBtn").disabled=!!cd.protect||state.securityPaused>0;$("guardBtn").disabled=state.securityPaused>0;
 $("guardStatus").innerHTML=(state.guards||[]).map(g=>`<div class="miniCard"><b>${g.name}</b><br>${g.target?`→ ${ROOM[g.target]} · ${Math.ceil(g.arriveIn/1000)}s`:`At ${ROOM[g.room]}`}</div>`).join("");$("incidentFeed").innerHTML=[...(state.feed||[])].reverse().map(x=>`<div class="feedItem"><small>${new Date(x.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}${x.room?` · ${ROOM[x.room]}`:""}</small><b>${esc(x.text)}</b></div>`).join("")||"<small>No incidents yet.</small>";}
$("cameraBtn").onclick=()=>act("bank_heist_hq_camera",{room:$("cameraRoom").value});$("guardBtn").onclick=()=>act("bank_heist_hq_guard",{guardId:$("guardId").value,room:$("guardRoom").value});$("lockBtn").onclick=()=>{const [a,b]=$("lockEdge").value.split("|");act("bank_heist_hq_lock",{a,b})};$("scanBtn").onclick=()=>act("bank_heist_hq_scan",{zone:$("scanZone").value});$("protectBtn").onclick=()=>act("bank_heist_hq_protect",{exit:$("protectExit").value});
function renderComms(){const chat=state.chat||[];$("chat").innerHTML=chat.map(m=>`<div class="msg ${m.from==="system"?"system":(role==="hq"?m.from==="mikael":m.from==="lizzy")?"me":""}">${esc(m.text)}<small>${m.from==="mikael"?"Mikael":m.from==="lizzy"?"Lizzy":"Bank System"}</small></div>`).join("");$("chat").scrollTop=$("chat").scrollHeight;const d=state.deal;$("dealBox").classList.toggle("hidden",!d);if(d)$("dealBox").innerHTML=`<b>${d.type==="headstart"?"5-second head start":"Bribe negotiation"}</b><br>${d.status==="countered"?`Mikael countered at MB${Number(d.counter).toLocaleString()}.`:`Lizzy offered MB${Number(d.offer).toLocaleString()}.`}<br>Status: ${esc(d.status.replaceAll("_"," "))}`;
 if(role==="lizzy"){$("dealControls").innerHTML=(d?.status==="countered")?`<button data-deal-reply="accept">Accept MB${Number(d.counter).toLocaleString()}</button><button data-deal-reply="reject">Reject counter</button>`:`<button id="headstartDeal">Offer MB1,000 for 5s head start</button><button id="bribeBtn">Offer bribe</button>`;$("announcements").classList.add("hidden");$("headstartDeal")?.addEventListener("click",()=>act("bank_heist_lizzy_deal",{dealType:"headstart"}));$("bribeBtn")?.addEventListener("click",()=>$("bribeDialog").showModal());qa("[data-deal-reply]").forEach(b=>b.onclick=()=>act("bank_heist_lizzy_deal_reply",{decision:b.dataset.dealReply}));}
 else{$("dealControls").innerHTML=d?.status==="pending_hq"?`<button data-hqdeal="accept">Accept</button><button data-hqdeal="reject">Reject</button><button data-hqdeal="counter">Demand more</button>`:"";qa("[data-hqdeal]").forEach(b=>b.onclick=()=>{if(b.dataset.hqdeal==="counter"){const v=prompt("Counter amount in MB",String((d.offer||0)+1000));if(v)act("bank_heist_hq_deal",{decision:"counter",counter:Number(v)})}else act("bank_heist_hq_deal",{decision:b.dataset.hqdeal})});$("announcements").classList.remove("hidden");$("announcements").innerHTML=["The bank is temporarily closed due to one specific woman.","Lizzy, return the money. This is affecting my presidency.","This is not a withdrawal. I checked.","Security would like everyone to stop being dramatic."].map(x=>`<button data-ann="${esc(x)}">📢 ${esc(x)}</button>`).join("");qa("[data-ann]").forEach(b=>b.onclick=()=>act("bank_heist_hq_announcement",{text:b.dataset.ann}));}}
$("chatForm").onsubmit=e=>{e.preventDefault();const t=$("chatInput").value.trim();if(!t)return;$("chatInput").value="";act("bank_heist_chat",{role,text:t})};$("bribeForm").onsubmit=e=>{e.preventDefault();$("bribeDialog").close();act("bank_heist_lizzy_deal",{dealType:"bribe",offer:Number($("bribeAmount").value)})};
function applyPayout(){if(role!=="lizzy"||state.phase!=="escaped"||!state.payout)return;const k=`bankHeistPayoutApplied:${state.run}`;if(localStorage.getItem(k))return;const walletKey="lizzyMickyBucsV1",before=Math.max(0,Number(localStorage.getItem(walletKey)||0)),after=before+Number(state.payout||0);localStorage.setItem(walletKey,String(after));localStorage.setItem(k,String(state.payout));window.dispatchEvent(new CustomEvent("mickyBucsBalanceChanged",{detail:{balance:after,source:"bank-heist"}}));}
function renderEnd(){if(!["escaped","caught","timeout"].includes(state.phase)||lastEndRun===state.run)return;lastEndRun=state.run;const lizzyWin=state.phase==="escaped";$("endPortrait").src=lizzyWin?"heist-assets/lizzy.jpg":"heist-assets/mikael.jpg";$("endEyebrow").textContent=lizzyWin?"WITHDRAWAL SUCCESSFUL, APPARENTLY":"BANK OF MICKY SECURITY";$("endTitle").textContent=lizzyWin?"LIZZY ESCAPED":"MIKAEL CAUGHT HER";$("endText").textContent=lizzyWin?`Escape route: ${ROOM[state.reason]||state.reason}.`:state.phase==="timeout"?"The 15-minute lockdown expired before Lizzy got out.":"Three security interceptions ended the heist.";$("endMoney").textContent=lizzyWin?`Escaped with MB${Number(state.escapedWith||0).toLocaleString()} → 5% kept = MB${Number(state.payout||0).toLocaleString()}`:"No heist payout.";$("endScreen").classList.remove("hidden")}
$("endClose").onclick=()=>$("endScreen").classList.add("hidden");
function tick(){if(!state)return;const left=state.phase==="active"?Math.max(0,state.endAt-now()):state.phase==="lobby"?15*60*1000:0;$("timer").textContent=fmt(left);if(state.phase==="active"){if(role==="lizzy"&&state.threat){$("dangerBanner").textContent=`🚨 SECURITY SEARCH IN ${Math.max(0,Math.ceil((state.threat.searchIn-(now()-state.serverNow))/1000))}s — hide, leave or jam.`}if(role==="hq"&&state.securityPaused>0)$("hqResult").textContent=`🤝 DEAL ACTIVE — security controls paused for ${Math.max(0,Math.ceil((state.securityPaused-(now()-state.serverNow))/1000))}s.`}}
setInterval(tick,250);
$("settingsBtn").onclick=()=>{$("workerUrl").value=getWorker();$("hqKeyLabel").classList.toggle("hidden",role!=="hq");$("hqKeyInput").value=getKey();$("settings").showModal()};$("saveSettings").onclick=e=>{e.preventDefault();worker=$("workerUrl").value.trim();if(worker){localStorage.setItem("bankHeistWorkerUrl",worker);localStorage.setItem(role==="hq"?"mickyhq_test_worker_url_v1":"lizzyos_test_worker_url_v1",worker)}else localStorage.removeItem("bankHeistWorkerUrl");if(role==="hq"){hqKey=$("hqKeyInput").value.trim();if(hqKey)localStorage.setItem("bankHeistHqKey",hqKey)}$("settings").close();refresh()};$("toggleComms").onclick=()=>document.getElementById("app").classList.toggle("commsClosed");
window.addEventListener("resize",()=>{if(role==="hq"&&state)renderMap()});document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh()});setInterval(refresh,1300);refresh();
})();
