"use strict";
(function(){
const APP="lizzyInteractiveRewardsProductionV3",VIP="lizzyInteractiveVipProductionV3",LEGACYVIP="lizzyVipStateV1",TOKENS="lizzyTokenJarV1",WALLET="lizzyMickyBucsV1",SHELF="lizzySecretShelfV1",LETTERS="lizzyPurchasedLettersV1",PREP="lizzyInteractiveRewardsPreparedV3",DAY=86400000;
const $=id=>document.getElementById(id),now=()=>Date.now(),read=(k,f)=>{try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ITEMS=[{id:"letter_002",icon:"💌",name:"Unreleased Letter #002",kind:"letter",teaser:"An unreleased letter. Contents unavailable before purchase."},{id:"mystery_reward",icon:"🎁",name:"Mystery Reward",kind:"token",teaser:"Contents remain classified until the deal is complete."},{id:"archive_x17",icon:"🗃️",name:"Sealed Archive X-17",kind:"document",teaser:"Origin: REDACTED • Contents: SEALED • Clearance: UNKNOWN"},{id:"dossier_001",icon:"📁",name:"Classified File #001",kind:"dossier",teaser:"SUBJECT DATA: REDACTED • CASE: #001"},{id:"hater_file",icon:"📁",name:"Classified File #002",kind:"dossier",teaser:"CASE: #002-H8R • CONTENTS: CLASSIFIED"},{id:"mrperfect_file",icon:"📁",name:"Classified File #003",kind:"dossier",teaser:"CASE: #003-MP • ULTRA SECRET"},{id:"letter_003",icon:"💌",name:"Unreleased Letter #003",kind:"letter",teaser:"An unreleased letter. Contents unavailable before purchase."},{id:"letter_004",icon:"💌",name:"Unreleased Letter #004",kind:"letter",teaser:"An unreleased letter. Contents unavailable before purchase."},{id:"o4e_004",icon:"👓",name:"Classified File #004",kind:"dossier",teaser:"CASE: O4E-004 • SUBJECT DATA: REDACTED"},{id:"mwa_005",icon:"🎯",name:"Classified File #005",kind:"dossier",teaser:"FILE: MWA-005 • VULNERABILITIES: CLASSIFIED"},{id:"aypp_006",icon:"🔐",name:"Classified File #006",kind:"dossier",teaser:"FILE: AYPP-006 • ENCRYPTED • CLEARANCE REQUIRED"}];
const EYES=`Lizzy,

If I had to pick one thing about you, it would probably be your eyes.

And yes, I know that saying this is dangerous because your ego really doesn't need any additional funding.

But I notice them. A lot.

There's just something about your eyes that constantly bamboozles me. Whether you're smiling, giving me attitude, looking at me like I've said the dumbest thing imaginable, or just looking at me normally — they always get me.

I've even tried looking at your forehead instead.

Didn't work.

So unfortunately, I think I'll just continue taking the risk and looking into them.

And before you get too excited about this letter, this does not mean I'm becoming soft.

This message will self-destruct the moment you try using it against me.

Mikael
a.k.a Mr Perfect 💜`;
const HONEST=`Lizzy,

Congratulations. You have somehow unlocked a very rare event:

Mikael being nice without immediately ruining it.

So, for the next few moments, I'll admit something.

I genuinely enjoy having you around.

I've gotten used to the attitude, the ragebaiting, the random arguments, you being a menace for absolutely no reason, and somehow constantly bamboozling me with how pretty and beautiful you are and stuff.

And underneath all of that, you're genuinely someone I appreciate a lot.

You're funny, caring, ridiculously easy to talk to, and somehow you manage to make ordinary moments way more entertaining than they should be.

I notice more about you than I probably admit.

And I'm very glad I met you.

Okay.

Temporary Honesty has now expired.

Any attempt to question Mikael about the contents of this letter may result in immediate denial and accusations of fabricated evidence.

Mikael
a.k.a Mr Perfect 💜`;
const INTERACTIONS=[{name:"Song Exchange",emoji:"🎧",desc:"Mikael and Lizzy each send one song that reminds them of the other, with a short explanation why."},{name:"Question Call",emoji:"📞",desc:"A 10-minute call where Lizzy can ask Mikael questions and he answers honestly, with reasonable privacy vetoes."},{name:"Voice Note Request",emoji:"🎤",desc:"Lizzy may request one voice note from Mikael on a topic of her choice."},{name:"Truth Card",emoji:"🃏",desc:"Lizzy may ask Mikael one question and he has to answer truthfully, with reasonable privacy boundaries."}];
function base(){return{vip:{owned:1,status:"ready"},rareBox:{owned:1,status:"unopened"}}}function state(){const b=base(),x=read(APP,{});return{...b,...x,vip:{...b.vip,...(x.vip||{})},rareBox:{...b.rareBox,...(x.rareBox||{})}}}function save(s){write(APP,s)}function vip(){return read(VIP,null)}function active(){const v=vip();return!!(v&&Number(v.expiresAt)>now())}function saveVip(v){write(VIP,v);write(LEGACYVIP,v)}function wallet(){return Math.max(0,Number(localStorage.getItem(WALLET)||0))}function setWallet(n){localStorage.setItem(WALLET,String(Math.max(0,Math.floor(Number(n)||0))));window.dispatchEvent(new Event("lizzyStoreRefresh"))}function fmt(ms){ms=Math.max(0,ms);const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1000);return{short:`${h}h ${String(m).padStart(2,"0")}m`,full:`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}}function day(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function notify(type,data){setTimeout(()=>{try{const u=window.LIZZY_TELEGRAM_WORKER_URL||"https://lizzyos-notifications.mulaudzimikael73.workers.dev/";fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,...data,createdAt:new Date().toISOString()})}).catch(()=>{})}catch{}},0)}
function prepare(){if(localStorage.getItem(PREP))return;const t=read(TOKENS,null);if(t){t.inventory=t.inventory||{};delete t.inventory["VIP Status — One Day"];delete t.inventory["VIP Status - One Day"];delete t.inventory["Mystery Rare Box"];if(Array.isArray(t.history))t.history=t.history.filter(x=>!/VIP Status|Mystery Rare Box/i.test(String(x?.name||"")));write(TOKENS,t)}const s=state();if(!active()){s.vip.owned=Math.max(1,Number(s.vip.owned)||0);s.vip.status="ready"}s.rareBox.owned=Math.max(1,Number(s.rareBox.owned)||0);s.rareBox.status="unopened";save(s);localStorage.setItem(PREP,"done")}
function open(){const w=$("interactiveRewardsWindow");if(!w)return false;w.classList.remove("hidden");w.style.display="block";$("irStage")?.classList.add("hidden");render();return true}function close(){const w=$("interactiveRewardsWindow");if(w){w.classList.add("hidden");w.style.removeProperty("display")}return true}function stage(h){const x=$("irStage");x.classList.remove("hidden");x.innerHTML=h;return x}function action(h){if($("irVipAction"))$("irVipAction").innerHTML=h}
function allowance(){if(!active())return;const v=vip(),d=day();if(v.lastAllowanceDay===d)return;v.lastAllowanceDay=d;v.allowanceEarned=Number(v.allowanceEarned||0)+3;saveVip(v);setWallet(wallet()+3);notify("vip_privilege",{privilege:"daily_allowance",amount:3,balance:wallet()})}
function render(){const s=state(),v=vip(),on=active();if(s.vip.status==="active"&&!on){s.vip.status="expired";s.vip.owned=0;save(s)}$("irVipBadge")?.classList.toggle("hidden",!on);if(on&&v){const f=fmt(v.expiresAt-now());$("irVipClock").textContent=f.short;if($("irVipActivationClock"))$("irVipActivationClock").textContent=f.full}const n=(Number(s.vip.owned)>0?1:0)+(Number(s.rareBox.owned)>0?1:0);if($("irCount"))$("irCount").textContent=`${n} reward${n===1?"":"s"} available`;if($("irDesktopDot")){$("irDesktopDot").textContent=n;$("irDesktopDot").classList.toggle("hidden",n===0)}const vs=on?`ACTIVE • ${fmt(v.expiresAt-now()).short}`:s.vip.status==="expired"?"EXPIRED":"READY TO ACTIVATE";$("irCards").innerHTML=`<article class="irCard"><div class="irCardEmoji">👑</div><h2>VIP Status — One Day</h2><div class="irStatus">${vs}</div><p>24 hours of VIP privileges, better reward odds and bonuses.</p><button id="irVipOpen" ${Number(s.vip.owned)<=0||on?"disabled":""}>${on?"VIP ACTIVE":"ACTIVATE VIP"}</button>${on?'<button id="irVipControlsBtn" class="irSecondaryBtn">OPEN VIP CONTROLS</button>':""}</article><article class="irCard"><div class="irCardEmoji">🎁</div><h2>Mystery Rare Box</h2><div class="irStatus">${s.rareBox.status==="unopened"?"UNOPENED":"OPENED"}</div><p>Money, Secrets or Mikael.</p><button id="irRareOpen" ${Number(s.rareBox.owned)<=0?"disabled":""}>${Number(s.rareBox.owned)>0?"OPEN RARE BOX":"OPENED"}</button></article>`;$("irVipOpen")?.addEventListener("click",confirmVip);$("irVipControlsBtn")?.addEventListener("click",controls);$("irRareOpen")?.addEventListener("click",rare);allowance()}
function confirmVip(){if(active())return controls();const s=state();if(Number(s.vip.owned)<=0)return;const x=stage(`<div class="irConfirmCard"><div class="irBigEmoji">👑</div><h2>Activate VIP Status?</h2><p>The 24-hour timer starts immediately.</p><button id="irConfirmVip">ACTIVATE 24-HOUR VIP ✨</button></div>`);x.querySelector("#irConfirmVip").onclick=activate}
function confetti(){for(let i=0;i<100;i++){const p=document.createElement("span");p.className="irConfetti";p.textContent=["👑","✨","💜","💎","⭐"][i%5];p.style.left=Math.random()*100+"vw";document.body.appendChild(p);setTimeout(()=>p.remove(),3500)}}
function activate(){const s=state();if(active()||Number(s.vip.owned)<=0)return;const st=now(),ex=st+DAY,v={startedAt:st,expiresAt:ex,peeks:2,reroll:1,override:1,discount:1,mysteryBoost:true,arcadeBonusCap:5,arcadeBonusEarned:0,allowanceEarned:0,lastAllowanceDay:null,complaints:0,messages:0};saveVip(v);s.vip.owned--;s.vip.status="active";save(s);close();$("irVipActivation").classList.remove("hidden");$("irVipActivation").style.display="grid";confetti();allowance();render();notify("interactive_reward",{reward:"VIP Status — One Day",status:"activated",expiresAt:ex})}
function enter(){const o=$("irVipActivation");o.classList.add("hidden");o.style.removeProperty("display");controls()}function saveV(fn){const v=vip();if(!v||!active())return null;fn(v);saveVip(v);return v}
function controls(){if(!active())return open();const v=vip();$("irVipActivation")?.classList.add("hidden");const w=$("interactiveRewardsWindow");w.classList.remove("hidden");w.style.display="block";const x=stage(`<div class="irVipControls"><div class="irBigEmoji">👑</div><h2>VIP Control Panel</h2><p><b>${fmt(v.expiresAt-now()).short}</b> remaining • Arcade ${v.arcadeBonusEarned||0}/${v.arcadeBonusCap||5} MB • Allowance ${v.allowanceEarned||0} MB</p><div class="irChoiceGrid"><button data-v="peek" ${v.peeks<=0?"disabled":""}>🔐 <b>Classified Sneak Peek</b><small>${v.peeks}/2 remaining</small></button><button data-v="reroll" ${v.reroll<=0?"disabled":""}>🎁 <b>Daily Reward Reroll</b><small>${v.reroll} remaining</small></button><button data-v="override" ${v.override<=0?"disabled":""}>⚖️ <b>VIP Override</b><small>${v.override} remaining</small></button><button data-v="discount" ${v.discount<=0?"disabled":""}>🛍️ <b>Secret Shelf Discount</b><small>${v.discount?"10% off one purchase":"Used"}</small></button><button data-v="complaint">📣 <b>Complaint Against Mikael</b></button><button data-v="message">💌 <b>Message Mr Perfect</b></button></div><div id="irVipAction" class="irVipAction">Choose a VIP privilege.</div></div>`);x.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>feature(b.dataset.v))}
function threeLines(text){const a=String(text||"").replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean);if(a.length>=3)return a.slice(0,3);return (String(text||"").replace(/\s+/g," ").match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).map(x=>x.trim()).filter(Boolean).slice(0,3)}
function actualContent(i){let l=read(LETTERS,[]);if(Array.isArray(l)){const h=l.find(x=>x&&(x.id===i.id||x.title===i.name));if(h?.content)return h.content}const s=read(SHELF,{});for(const q of [s?.items,s?.catalog,s?.content,s?.files]){if(Array.isArray(q)){const h=q.find(x=>x&&(x.id===i.id||x.name===i.name||x.publicName===i.name));if(h)return h.content||h.text||h.body||h.fullContent||""}else if(q&&typeof q==="object"&&q[i.id]){const h=q[i.id];return typeof h==="string"?h:(h.content||h.text||h.body||h.fullContent||"")}}return""}
function extract3(i){const r=threeLines(actualContent(i));if(r.length>=3)return r;const f={letter_002:["CLASSIFIED LETTER EXTRACT","There is something Mikael has not said out loud yet.","Everything after this line remains sealed."],letter_003:["CLASSIFIED LETTER EXTRACT","This letter was written for a very specific Lizzy moment.","Only three lines have been cleared for viewing."],letter_004:["CLASSIFIED LETTER EXTRACT","Mikael knew exactly what he wanted this letter to say.","Unfortunately for Lizzy, the rest remains classified."],dossier_001:["DOSSIER EXTRACT — CASE #001","Subject behaviour has been observed more closely than she realises.","Further evidence remains classified."],hater_file:["DOSSIER EXTRACT — CASE #002-H8R","Multiple allegations of elite-level hating remain under investigation.","Supporting evidence remains classified."],mrperfect_file:["DOSSIER EXTRACT — CASE #003-MP","Subject: Mr Perfect. Confidence levels remain suspiciously high.","Additional findings have been sealed by order of Mikael."],o4e_004:["DOSSIER EXTRACT — O4E-004","Optical evidence has been logged and marked highly distracting.","The remaining observations require higher clearance."],mwa_005:["DOSSIER EXTRACT — MWA-005","A potential Mikael weakness has been identified.","Exact vulnerability details remain encrypted."],aypp_006:["DOSSIER EXTRACT — AYPP-006","Agent Yelizaveta profile contains several restricted observations.","Only three lines have been approved for this intelligence drop."],archive_x17:["ARCHIVE X-17 — PARTIAL DECRYPTION","The archive contains material Lizzy was not originally cleared to see.","Decryption terminated automatically after line three."],mystery_reward:["MYSTERY REWARD — PARTIAL INTEL","The sealed reward contains more than its public label suggests.","Full contents remain locked until proper redemption."]};return f[i.id]||["CLASSIFIED EXTRACT",i.name,i.teaser]}
function show3(i,title){const a=extract3(i);return `<div class="irBigEmoji">${i.icon}</div><h3>${esc(title||i.name)}</h3><div class="irThreeLineReveal">${a.slice(0,3).map((x,n)=>`<p><b>${n+1}.</b> ${esc(x)}</p>`).join("")}</div><small>🔒 Only 3 lines were declassified. The full item remains locked.</small>`}
function locked(kind){const sh=read(SHELF,{owned:{}});return ITEMS.filter(i=>!sh?.owned?.[i.id]&&(!kind||i.kind===kind))}function peekSelector(src){const list=locked();if(!list.length)return action("Everything on the Secret Shelf is already owned.");action(`<b>🔐 SELECT A LOCKED ITEM</b><div class="irPeekGrid">${list.map(i=>`<button data-p="${i.id}">${i.icon} <b>${esc(i.name)}</b><small>${i.kind}</small></button>`).join("")}</div>`);$("irVipAction").querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>usePeek(b.dataset.p,src))}function usePeek(id,src){const i=ITEMS.find(x=>x.id===id);if(!i)return;if(src==="vip"){if(vip().peeks<=0)return;saveV(v=>v.peeks--);notify("vip_privilege",{privilege:"classified_sneak_peek",item:i.name,remaining:vip().peeks})}else{const c=Number(localStorage.getItem("lizzyRareSecretPeekCredits")||0);if(c<=0)return;localStorage.setItem("lizzyRareSecretPeekCredits",String(c-1))}action(show3(i,i.name))}
function feature(f){if(f==="peek")return vip().peeks>0&&peekSelector("vip");if(f==="reroll"){if(vip().reroll<=0)return;localStorage.setItem("lizzyVipRewardReroll","1");saveV(v=>v.reroll=0);action("🎁 <b>VIP REROLL ARMED.</b><br>Open Daily Rewards and use the VIP REROLL button.");notify("vip_privilege",{privilege:"daily_reward_reroll"});return}if(f==="discount"){if(vip().discount<=0)return;localStorage.setItem("lizzyVipShelfDiscount","10");saveV(v=>v.discount=0);action("🛍️ <b>10% DISCOUNT ACTIVE.</b><br>Your next accepted Secret Shelf purchase costs 10% less.");notify("vip_privilege",{privilege:"secret_shelf_discount",discount:10});return}if(f==="override"){if(vip().override<=0)return;action(`<b>⚖️ VIP OVERRIDE</b><textarea id="irVipText" class="irVipTextarea"></textarea><button id="irUseOverride">USE OVERRIDE</button>`);$("irUseOverride").onclick=()=>{const t=$("irVipText").value.trim();if(!t)return;saveV(v=>v.override=0);action(`⚖️ <b>OVERRIDDEN:</b> ${esc(t)}`);notify("vip_privilege",{privilege:"override",ruling:t})};return}if(f==="complaint"){action(`<b>📣 VIP COMPLAINT</b><textarea id="irVipText" class="irVipTextarea"></textarea><button id="irSubmitComplaint">SUBMIT</button>`);$("irSubmitComplaint").onclick=()=>{const t=$("irVipText").value.trim();if(!t)return;action("Complaint received. Position 1 of 1. Mikael accountability: 2% 😂");notify("vip_complaint",{complaint:t,accountabilityChance:"2%"})};return}if(f==="message"){action(`<b>💌 VIP MESSAGE</b><textarea id="irVipText" class="irVipTextarea"></textarea><button id="irSubmitMessage">SEND</button>`);$("irSubmitMessage").onclick=()=>{const t=$("irVipText").value.trim();if(!t)return;action("Priority message sent 💌");notify("vip_priority_message",{message:t})}}}
function arcade(){if(!active())return;const v=vip();if((v.arcadeBonusEarned||0)>=(v.arcadeBonusCap||5))return;v.arcadeBonusEarned=(v.arcadeBonusEarned||0)+1;saveVip(v);setWallet(wallet()+1);notify("vip_privilege",{privilege:"arcade_bonus",amount:1,earned:v.arcadeBonusEarned,balance:wallet()})}
function consume(){const s=state();if(s.rareBox.owned<=0)return false;s.rareBox.owned--;s.rareBox.status=s.rareBox.owned>0?"unopened":"opened";save(s);return true}function rare(){if(state().rareBox.owned<=0)return;const x=stage(`<div class="irBigEmoji">🎁</div><h2>Choose Your Mystery</h2><div class="irChoiceGrid"><button data-r="money">💰 <b>MONEY</b><small>20–50 Micky Bucs</small></button><button data-r="secrets">🔐 <b>SECRETS</b><small>Classified advantage</small></button><button data-r="mikael">❤️ <b>MIKAEL</b><small>Letter or interaction</small></button></div>`);x.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>resolve(b.dataset.r))}
function reveal(h){const x=stage(`<div class="irRareReveal">${h}<button id="irDone" class="irSecondaryBtn">DONE</button></div>`);x.querySelector("#irDone").onclick=()=>{$("irStage").classList.add("hidden");render()}}
function resolve(cat){document.querySelectorAll("[data-r]").forEach(b=>b.disabled=true);if(!consume())return;if(cat==="money"){const n=20+Math.floor(Math.random()*31);setWallet(wallet()+n);reveal(`<div class="irBigEmoji">💰</div><h2>+${n} MICKY BUCS</h2><p>New balance: <b>${wallet()} MB</b></p>`);notify("rare_box_redeemed",{category:"Money",reward:`${n} Micky Bucs`,balance:wallet()});return}if(cat==="secrets"){const p=["peek","discount","intel"][Math.floor(Math.random()*3)];if(p==="peek"){localStorage.setItem("lizzyRareSecretPeekCredits","1");reveal(`<h2>🔐 CLASSIFIED SNEAK PEEK</h2><button id="irUseRarePeek">USE NOW</button>`);$("irUseRarePeek").onclick=rarePeek;notify("rare_box_redeemed",{category:"Secrets",reward:"Classified Sneak Peek"});return}if(p==="discount"){localStorage.setItem("lizzyRareShelfDiscount","15");reveal(`<h2>🛍️ 15% SECRET SHELF DISCOUNT</h2><p>Applied to your next accepted purchase.</p>`);notify("rare_box_redeemed",{category:"Secrets",reward:"15% Secret Shelf Discount"});return}const ds=locked("dossier"),i=ds.length?ds[Math.floor(Math.random()*ds.length)]:locked()[0];reveal(i?show3(i,`Dossier Intelligence — ${i.name}`):`<h2>🗂️ NO LOCKED DOSSIER</h2><p>Everything is already owned.</p>`);notify("rare_box_redeemed",{category:"Secrets",reward:"Dossier Intelligence — 3-Line Reveal",item:i?.name||"none"});return}const pool=["eyes","honesty","song","call","voice","truth"],p=pool[Math.floor(Math.random()*pool.length)];if(p==="eyes"||p==="honesty"){const e=p==="eyes",id=e?"rare_letter_eyes":"rare_letter_honesty",title=e?"One Thing About You…":"Temporary Honesty",content=e?EYES:HONEST;let l=read(LETTERS,[]);if(!Array.isArray(l))l=[];if(!l.some(x=>x.id===id))l.push({id,title,content,folder:"open_when_purchased",source:"Mystery Rare Box",purchasedAt:new Date().toISOString()});write(LETTERS,l);window.dispatchEvent(new Event("lizzyPurchasedLettersUpdated"));reveal(`<h2>💌 ${esc(title)}</h2><p>Saved to Open When → Purchased Letters.</p><details class="irLetterPreview"><summary>Read now</summary><pre>${esc(content)}</pre></details>`);notify("rare_box_redeemed",{category:"Mikael",reward:title,type:"Mystery Letter"});return}const nm={song:"Song Exchange",call:"Question Call",voice:"Voice Note Request",truth:"Truth Card"}[p],r=INTERACTIONS.find(x=>x.name===nm),t=read(TOKENS,{version:1,inventory:{},history:[]});t.inventory=t.inventory||{};t.inventory[r.name]=(t.inventory[r.name]||0)+1;write(TOKENS,t);window.dispatchEvent(new Event("lizzyTokenJarUpdated"));reveal(`<h2>${r.emoji} ${r.name}</h2><p>${r.desc}</p><p>Saved to Token Jar.</p>`);notify("rare_box_redeemed",{category:"Mikael",reward:r.name,type:"Mystery Interaction"})}
function rarePeek(){stage(`<div class="irBigEmoji">🔐</div><h2>Rare Box Sneak Peek</h2><div id="irVipAction" class="irVipAction"></div>`);peekSelector("rare")}
function grant(n){const s=state();if(/VIP Status/i.test(n)){s.vip.owned++;s.vip.status=active()?"active":"ready"}if(/Mystery Rare Box/i.test(n)){s.rareBox.owned++;s.rareBox.status="unopened"}save(s);render()}function capture(e){const r=e?.detail?.reward,n=Array.isArray(r)?String(r[2]||""):String(r?.name||r||"");if(!/VIP Status|Mystery Rare Box/i.test(n))return;e.stopImmediatePropagation();grant(n)}
function init(){prepare();$("interactiveRewardsIcon")?.addEventListener("click",open);$("irClose")?.addEventListener("click",close);$("irEnterVip")?.addEventListener("click",enter);$("irVipBadge")?.addEventListener("click",controls);window.addEventListener("lizzyDailyRewardClaimed",capture,true);window.addEventListener("lizzyGameCompleted",arcade);render();setInterval(render,1000)}
window.InteractiveRewardsApp={open,close,render,activateVip:activate,openVipControls:controls,showRareBox:rare,resolveRareBox:resolve,grant,state,vipIsActive:active};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();