(()=>{
"use strict";
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const KEY="lizzyLifeTestV1", WORKER=()=>String(window.LIZZY_TELEGRAM_WORKER_URL||"").trim();
const MONTHS=[["January",31],["February",28],["March",31],["April",30],["May",31],["June",30],["July",31],["August",31],["September",30],["October",31],["November",30],["December",31]];
const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const DIETS={junk:{name:"Junk",cost:40,emoji:"🍟"},balanced:{name:"Balanced",cost:70,emoji:"🥗"},healthy:{name:"Healthy",cost:110,emoji:"🥑"}};
const HOMES={family:{name:"Mom's House",rent:0,buy:0,emoji:"🏡",owned:false},sketchy:{name:"Sketchy Apartment",rent:90,buy:3200,emoji:"🏚️"},decent:{name:"Decent Apartment",rent:200,buy:7000,emoji:"🏢"},luxury:{name:"Luxury Apartment",rent:450,buy:16000,emoji:"🌇"}};
const JOBS={potato:{name:"Potato Industries",salary:28,emoji:"🥔"},paperclips:{name:"Micky's Executive Paperclips",salary:34,emoji:"📎"},bluetooth:{name:"Bluetooth Water Co.",salary:31,emoji:"💧"}};
const HOLIDAYS={"1-1":"🥂 New Year's Day","2-14":"❤️ Valentine's Day","10-31":"🎃 Halloween","12-25":"🎄 Christmas"};
const rand=a=>a[Math.floor(Math.random()*a.length)], clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const uid=p=>`${p}-${crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`;
function baseState(){return{version:1,lifeMinute:8*60,paused:false,speed:"normal",cash:650,
 routine:{autoWork:true,autoSleep:true,exercisePerWeek:3,family:"occasionally",autoSpend:false,cravings:"ask",dates:"ask",majorPurchases:"ask",attendPlans:true},
 job:{id:"potato",...JOBS.potato,employed:true,missedConsecutive:0,careerXP:0,performance:50,lastMiniDay:-1,skipNextWork:false},
 home:{id:"family",...HOMES.family,owned:false,nextRentAbsDay:31},diet:{id:"balanced",...DIETS.balanced,nextRenewAbsDay:14,autoRenew:true},
 loans:[],legal:[],plans:[],pending:[],history:[{year:1,text:"Lizzy Life began. Nobody has been fired yet. Suspicious.",icon:"🎮"}],activity:[],
 relationship:{mikael:{status:"Friends",trust:55,friendship:60,annoyance:4}},
 stats:{earned:0,spent:0,jobsHeld:1,fired:0,lawsuits:0,lawsuitsWon:0,mikaelDates:0,npcDates:0,bossArguments:0,loansTaken:0,properties:0,junkCravings:0},
 wrapped:null,simTicks:0};}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");return x&&x.version?Object.assign(baseState(),x):baseState()}catch{return baseState()}}
let s=load();
function save(){localStorage.setItem(KEY,JSON.stringify(s));}
function absDay(){return Math.floor(s.lifeMinute/1440)}
function dateParts(min=s.lifeMinute){const d=Math.floor(min/1440),year=Math.floor(d/365)+1,yd=d%365;let left=yd,mi=0;while(left>=MONTHS[mi][1])left-=MONTHS[mi++][1];const minute=((min%1440)+1440)%1440,h=Math.floor(minute/60),m=minute%60;return{absDay:d,year,month:mi+1,monthName:MONTHS[mi][0],day:left+1,dayName:DAYS[d%7],hour:h,minute:m,season:mi<=1||mi===11?"Summer":mi<=4?"Autumn":mi<=7?"Winter":"Spring",period:h<12?"Morning":h<17?"Afternoon":h<22?"Evening":"Night"}}
function lifeDate(min=s.lifeMinute){const p=dateParts(min);return `${p.dayName}, ${p.day} ${p.monthName} — Year ${p.year} · ${String(p.hour).padStart(2,"0")}:${String(p.minute).padStart(2,"0")} · ${p.season}`}
function addActivity(text,icon="•"){s.activity.push({day:absDay(),text,icon});s.activity=s.activity.slice(-80)}
function spend(n,reason){n=Math.max(0,Math.round(Number(n)||0));if(s.cash<n)return false;s.cash-=n;s.stats.spent+=n;addActivity(`-${n} LB · ${reason}`,"💸");return true}
function earn(n,reason){n=Math.max(0,Math.round(Number(n)||0));s.cash+=n;s.stats.earned+=n;addActivity(`+${n} LB · ${reason}`,"💰")}
function pushHistory(text,icon="📌"){s.history.push({year:dateParts().year,text,icon});s.history=s.history.slice(-120)}
function isWorkday(d){return d%7<5}
function fire(reason){if(!s.job?.employed)return;s.job.employed=false;s.job.missedConsecutive=0;s.stats.fired++;s.stats.bossArguments++;const c={id:uid("case"),reason,status:"not_requested",createdLifeMinute:s.lifeMinute};s.legal.push(c);addActivity(`FIRED: ${reason}`,"🔥");pushHistory(`Fired from ${s.job.name}: ${reason}`,"🔥")}
function processPlanDay(day){for(const p of s.plans.filter(x=>x.status==="accepted"&&Math.floor(x.lifeMinute/1440)===day)){if(s.routine.attendPlans!==false){p.status="attended";if(p.withMikael){s.relationship.mikael.trust=clamp(s.relationship.mikael.trust+3,0,100);s.relationship.mikael.friendship=clamp(s.relationship.mikael.friendship+4,0,100);s.stats.mikaelDates++;}addActivity(`Attended: ${p.title}`,"❤️");pushHistory(`Attended ${p.title}.`,"❤️")}else{p.status="missed";if(p.withMikael){s.relationship.mikael.trust=clamp(s.relationship.mikael.trust-10,0,100);s.relationship.mikael.annoyance=clamp(s.relationship.mikael.annoyance+15,0,100);}addActivity(`Missed plan: ${p.title}`,"😬")}}}
function householdEvent(){if(Math.random()>.16)return;const e=rand(["Sefura wants money again.","Mologadi has decided personal space is optional.","Mom needs help with something immediately.","Family dinner became a debate for no clear reason.","A shopping trip somehow became a full family expedition.","There has been a household argument over absolutely nothing."]);addActivity(e,"🏠")}
function dailyProcess(day,{autoWorkOverride=null,dry=false}={}){
 const p=dateParts(day*1440+12*60),work=isWorkday(day),autoWork=autoWorkOverride==null?s.routine.autoWork:autoWorkOverride;
 if(work&&s.job.employed){
   const miss=s.job.skipNextWork||!autoWork;s.job.skipNextWork=false;
   if(miss){s.job.missedConsecutive++;addActivity(`Missed work at ${s.job.name}. (${s.job.missedConsecutive}/3)`,"🚫");if(s.job.missedConsecutive>=3)fire("Three consecutive actual missed workdays. Your boss has discovered attendance records.")}
   else{s.job.missedConsecutive=0;earn(s.job.salary,`${s.job.name} salary`);s.job.performance=clamp(s.job.performance+1,0,100);if(Math.random()<.008)fire("Your manager says your desk plant has displayed greater leadership potential.")}
 }
 if(day>=s.diet.nextRenewAbsDay){if(s.diet.autoRenew&&spend(s.diet.cost,`${s.diet.name} groceries`)){s.diet.nextRenewAbsDay=day+14;addActivity(`${s.diet.name} diet auto-renewed for 14 days.`,"🛒")}else{if(!s.pending.some(x=>x.kind==="diet_due"&&x.status==="pending"))s.pending.push({id:uid("diet"),kind:"diet_due",title:"Groceries need attention",status:"pending",createdLifeMinute:s.lifeMinute});s.diet.nextRenewAbsDay=day+1}}
 if(!s.home.owned&&s.home.rent>0&&p.day===1){if(!spend(s.home.rent,`${s.home.name} rent`))addActivity(`Rent due: ${s.home.rent} LB. Balance is awkward.`,"🏚️")}
 for(const loan of s.loans.filter(x=>x.status==="active"&&day>=x.nextPaymentDay)){const pay=Math.min(loan.payment,loan.balance);if(spend(pay,`Bank of Micky loan payment`)){loan.balance-=pay;loan.nextPaymentDay=day+30;if(loan.balance<=0){loan.status="paid";addActivity("Bank of Micky loan fully repaid.","🏦")}}}
 processPlanDay(day);householdEvent();
 const holiday=HOLIDAYS[`${p.month}-${p.day}`];if(holiday)addActivity(holiday,"🎉");
}
function wrapYear(oldYear){s.wrapped={year:oldYear,stats:{...s.stats},text:`YEAR ${oldYear} WRAPPED`};pushHistory(`Year ${oldYear} wrapped: earned LB${s.stats.earned}, spent LB${s.stats.spent}, fired ${s.stats.fired} time${s.stats.fired===1?"":"s"}.`,"🎆");s.stats={earned:0,spent:0,jobsHeld:s.job.employed?1:0,fired:0,lawsuits:0,lawsuitsWon:0,mikaelDates:0,npcDates:0,bossArguments:0,loansTaken:0,properties:s.home.owned?1:0,junkCravings:0}}
function advanceMinutes(minutes,{autoWorkOverride=null,stopForProtected=false}={}){minutes=Math.max(0,Math.floor(minutes));if(!minutes)return{advanced:0};let remaining=minutes,advanced=0,startYear=dateParts().year;
 while(remaining>0){const curDay=absDay(),toMidnight=(curDay+1)*1440-s.lifeMinute,step=Math.min(remaining,toMidnight);s.lifeMinute+=step;remaining-=step;advanced+=step;if(step===toMidnight){const newDay=absDay();const y=dateParts().year;if(y!==startYear){wrapYear(startYear);startYear=y}dailyProcess(newDay,{autoWorkOverride});if(stopForProtected&&s.pending.some(x=>x.status==="pending"&&x.kind!=="diet_due"))break;}}
 save();render();pushSnapshot();return{advanced}}
function preview(days,autoWork=true){days=Math.max(1,Math.floor(days));let workdays=0;for(let i=1;i<=days;i++)if(isWorkday(absDay()+i))workdays++;const salary=s.job.employed&&autoWork?workdays*s.job.salary:0;const diet=Math.floor((days+Math.max(0,absDay()-s.diet.nextRenewAbsDay))/14)*s.diet.cost;let rent=0;for(let i=1;i<=days;i++){const p=dateParts((absDay()+i)*1440);if(!s.home.owned&&s.home.rent&&p.day===1)rent+=s.home.rent}const loan=s.loans.filter(x=>x.status==="active").reduce((sum,l)=>sum+Math.floor(days/30)*l.payment,0);return{days,workdays,salary,diet,rent,loan,expected:s.cash+salary-diet-rent-loan}}
function nextEventDays(){const d=absDay(),c=[];for(let i=1;i<=10;i++)if(isWorkday(d+i)&&s.job.employed){c.push(i);break}for(const p of s.plans.filter(x=>x.status==="accepted"&&x.lifeMinute>s.lifeMinute))c.push(Math.max(1,Math.ceil((p.lifeMinute-s.lifeMinute)/1440)));return c.length?Math.min(...c):1}
function applyInvite(c){if(s.pending.some(x=>x.id===c.id)||s.plans.some(x=>x.inviteId===c.id))return;s.pending.push({id:c.id,kind:"mikael_invite",title:c.title||"Plan with Mikael",detail:c.detail||"",daysAhead:Math.max(1,Number(c.daysAhead)||1),timeMinute:Number(c.timeMinute)||19*60,status:"pending",withMikael:true,createdLifeMinute:s.lifeMinute});addActivity(`New invitation from Mikael: ${c.title}`,"💌")}
function applyDecision(c){if(c.kind==="loan_decision"){const l=s.loans.find(x=>x.id===c.requestId);if(!l)return;if(c.decision==="approve"){l.status="active";l.payment=Math.max(1,Number(c.payment)||Math.ceil(l.amount/6));l.balance=l.amount;l.nextPaymentDay=absDay()+30;earn(l.amount,"Bank of Micky loan approved");s.stats.loansTaken++;}else l.status="rejected";addActivity(`Loan ${c.decision}.`,"🏦")}
 if(c.kind==="legal_decision"){const l=s.legal.find(x=>x.id===c.requestId);if(!l)return;l.status=c.decision==="accept"?"represented":"rejected";l.terms=c.terms||null;addActivity(c.decision==="accept"?"Mikael Spector accepted the case.":"Mikael Spector rejected the case.","⚖️")}
 if(c.kind==="recruitment"){if(s.pending.some(x=>x.id===c.id))return;s.pending.push({id:c.id,kind:"recruitment",title:c.title||"Government recruitment",detail:c.detail||"President Mikael wants to talk employment.",status:"pending",createdLifeMinute:s.lifeMinute})}}
async function api(action,body={}){const w=WORKER();if(!w)throw new Error("Test Worker not configured");const r=await fetch(w,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function getQueue(){const w=WORKER();if(!w)return[];const r=await fetch(w+`?action=life_queue`,{cache:"no-store"});const d=await r.json().catch(()=>({}));return r.ok?(d.commands||[]):[]}
function publicState(){return{lifeMinute:s.lifeMinute,date:lifeDate(),dateParts:dateParts(),paused:s.paused,speed:s.speed,cash:s.cash,job:s.job,home:s.home,diet:s.diet,routine:s.routine,loans:s.loans,legal:s.legal,plans:s.plans,pending:s.pending,relationship:s.relationship,stats:s.stats,activity:s.activity.slice(-30),history:s.history.slice(-40),wrapped:s.wrapped}}
async function pushSnapshot(){try{await api("life_snapshot_put",{snapshot:publicState()})}catch{}}
async function syncHQ(){try{const cmds=await getQueue(),ids=[];for(const c of cmds){try{if(c.kind==="life_invite")applyInvite(c);else applyDecision(c);ids.push(c.id)}catch{}}if(ids.length)await api("life_ack",{ids});if(ids.length){save();render()}await pushSnapshot()}catch{}}
function calendarItems(){const out=[],d=absDay();out.push({day:s.diet.nextRenewAbsDay,label:`${s.diet.emoji} ${s.diet.name} groceries · ${s.diet.cost} LB`});if(!s.home.owned&&s.home.rent){for(let i=1;i<=35;i++){const p=dateParts((d+i)*1440);if(p.day===1){out.push({day:d+i,label:`🏠 ${s.home.name} rent · ${s.home.rent} LB`});break}}}for(const l of s.loans.filter(x=>x.status==="active"))out.push({day:l.nextPaymentDay,label:`🏦 Loan payment · ${l.payment} LB`});for(const p of s.plans.filter(x=>x.status==="accepted"&&x.lifeMinute>s.lifeMinute))out.push({day:Math.floor(p.lifeMinute/1440),label:`❤️ ${p.title}`});return out.sort((a,b)=>a.day-b.day).slice(0,12)}
function pendingHtml(){const ps=s.pending.filter(x=>x.status==="pending");if(!ps.length)return'<div class="lifeEmpty">No protected decisions waiting.</div>';return ps.map(p=>`<article class="lifeDecision"><b>${esc(p.title)}</b><p>${esc(p.detail||"")}</p>${p.kind==="mikael_invite"?`<div><button data-life-decision="accept" data-id="${esc(p.id)}">❤️ Accept</button><button data-life-decision="reject" data-id="${esc(p.id)}">Reject</button><button data-life-decision="laugh" data-id="${esc(p.id)}">😂 Laugh</button><button data-life-decision="later" data-id="${esc(p.id)}">Later</button></div>`:p.kind==="recruitment"?`<div><button data-life-decision="accept" data-id="${esc(p.id)}">Attend Interview</button><button data-life-decision="reject" data-id="${esc(p.id)}">Decline</button></div>`:`<div><button data-life-decision="resolve" data-id="${esc(p.id)}">Handled</button></div>`}</article>`).join("")}
function render(){const root=$("lifeModeApp");if(!root)return;const p=dateParts(),job=s.job,rel=s.relationship.mikael,cal=calendarItems();root.innerHTML=`
 <div class="lifeHero"><div><small>LIFE TIME — NO REAL-WORLD CATCH-UP</small><h2>🎮 Lizzy Life</h2><strong>${esc(lifeDate())}</strong><span>${p.period}</span></div><div class="lifeCash">${Math.round(s.cash)}<small>Life Bucs</small></div></div>
 <div class="lifeControls"><button id="lifePause">${s.paused?"▶ Resume Life":"⏸ Pause Life"}</button><button data-life-speed="normal" class="${s.speed==="normal"?"on":""}">▶ Normal</button><button data-life-speed="fast" class="${s.speed==="fast"?"on":""}">▶▶ Fast</button><button id="lifeAdvancePeriod">+ Next Period</button><button id="lifeReset" class="dangerish">Reset Test Life</button></div>
 <div class="lifeNotice"><b>⏱️ Important:</b> closing Life Mode freezes this exact Life minute. There is no offline progression, no real-date comparison and no missed-time catch-up.</div>
 ${s.wrapped?`<div class="lifeWrapped"><b>🎆 YEAR ${s.wrapped.year} WRAPPED</b><span>Earned ${s.wrapped.stats.earned} LB · Spent ${s.wrapped.stats.spent} LB · Fired ${s.wrapped.stats.fired} · Mikael dates ${s.wrapped.stats.mikaelDates}</span><button id="lifeClearWrapped">Close</button></div>`:""}
 <div class="lifeGrid">
  <section class="lifeCard"><h3>💼 Work</h3><p>${job.employed?`${job.emoji} <b>${esc(job.name)}</b> · ${job.salary} LB/workday`:`🛋️ <b>Unemployed</b>`}</p><small>Consecutive actual missed workdays: ${job.missedConsecutive}/3</small><div class="lifeRow"><button id="lifeMiniGame" ${!job.employed?"disabled":""}>🎯 Optional Work Mini-Game</button><button id="lifeSkipWork" ${!job.employed?"disabled":""}>🚫 Skip Next Workday</button></div><p>Career XP ${job.careerXP} · Performance ${job.performance}%</p>${!job.employed?`<button id="lifeFindJob">📝 Find Another Job</button>${s.legal.some(x=>x.status==="not_requested")?`<button id="lifeRequestLawyer">⚖️ Request Mikael Spector</button>`:""}`:""}</section>
  <section class="lifeCard"><h3>🏠 Home</h3><p>${s.home.emoji} <b>${esc(s.home.name)}</b> · ${s.home.owned?"OWNED":s.home.rent?`${s.home.rent} LB/month`:"Living at home"}</p><div class="lifeHomeBtns">${Object.entries(HOMES).filter(([id])=>id!=="family").map(([id,h])=>`<button data-life-rent="${id}">Rent ${h.name}<small>${h.rent} LB/mo</small></button><button data-life-buy="${id}">Buy ${h.name}<small>${h.buy} LB</small></button>`).join("")}</div><button id="lifeMortgage">🏦 Ask Bank of Micky for a home loan</button></section>
  <section class="lifeCard"><h3>🛒 Diet</h3><p>${s.diet.emoji} <b>${s.diet.name}</b> · ${s.diet.cost} LB / 14 Life days</p><small>Renewal in ${Math.max(0,s.diet.nextRenewAbsDay-absDay())} Life day(s)</small><div class="lifeRow">${Object.entries(DIETS).map(([id,d])=>`<button data-life-diet="${id}" class="${s.diet.id===id?"on":""}">${d.emoji} ${d.name}</button>`).join("")}</div><label><input id="lifeDietAuto" type="checkbox" ${s.diet.autoRenew?"checked":""}> Auto-renew current diet</label></section>
  <section class="lifeCard"><h3>❤️ Mikael</h3><p>Status: <b>${esc(rel.status)}</b></p><div class="lifeMeters"><span>Trust <b>${rel.trust}</b></span><span>Friendship <b>${rel.friendship}</b></span><span>Annoyance <b>${rel.annoyance}</b></span></div><small>HQ invitations and President interactions use Life Time only.</small></section>
 </div>
 <div class="lifeGrid lifeGridWide">
  <section class="lifeCard"><h3>⏩ Skip Time</h3><div class="lifeSkipRow"><select id="lifeSkipDays"><option value="0">Skip to Tonight</option><option value="1">Skip 1 Day</option><option value="3">Skip 3 Days</option><option value="7">Skip 1 Week</option><option value="14">Skip 14 Days</option><option value="30">Skip 1 Month</option><option value="90">Skip 3 Months</option><option value="180">Skip 6 Months</option><option value="365">⚡ Fast Simulate 1 Life Year</option><option value="next">Skip to Next Payday / Plan</option><option value="custom">Custom days</option></select><input id="lifeCustomDays" type="number" min="1" max="3650" value="30" hidden><label><input id="lifeSkipWorkAuto" type="checkbox" checked> Auto-attend scheduled work</label><button id="lifePreviewSkip">Preview Skip</button></div><div id="lifeSkipPreview" class="lifePreview"></div></section>
  <section class="lifeCard"><h3>🧠 Auto Routine</h3><label><input data-routine="autoWork" type="checkbox" ${s.routine.autoWork?"checked":""}> Automatically attend work</label><label><input data-routine="autoSleep" type="checkbox" ${s.routine.autoSleep?"checked":""}> Automatically sleep</label><label><input data-routine="attendPlans" type="checkbox" ${s.routine.attendPlans?"checked":""}> Attend scheduled plans</label><label>Cravings <select data-routine-select="cravings"><option ${s.routine.cravings==="ask"?"selected":""}>ask</option><option ${s.routine.cravings==="auto"?"selected":""}>auto</option></select></label><label>Dates <select data-routine-select="dates"><option ${s.routine.dates==="ask"?"selected":""}>ask</option><option ${s.routine.dates==="auto"?"selected":""}>auto</option></select></label></section>
  <section class="lifeCard"><h3>🏦 Bank of Micky</h3><p>Loan applications wait for Mikael in Test HQ. Life keeps moving, but the money does not arrive until he approves.</p><div class="lifeRow"><input id="lifeLoanAmount" type="number" min="100" step="100" value="2500"><button id="lifeLoanApply">Request Loan</button></div><div>${s.loans.slice().reverse().slice(0,4).map(l=>`<small class="lifeLine">${Math.round(l.amount)} LB · ${esc(l.status)}${l.balance!=null?` · balance ${Math.round(l.balance)} LB`:""}</small>`).join("")||'<small>No loans yet.</small>'}</div></section>
 </div>
 <div class="lifeGrid lifeGridWide">
  <section class="lifeCard"><h3>🛑 Protected Decisions</h3>${pendingHtml()}</section>
  <section class="lifeCard"><h3>📅 Life Calendar</h3>${cal.map(c=>`<div class="lifeLine"><b>Day ${c.day+1}</b><span>${esc(c.label)}</span></div>`).join("")||'<div class="lifeEmpty">Nothing scheduled.</div>'}</section>
  <section class="lifeCard"><h3>📜 Life History</h3>${s.history.slice().reverse().slice(0,8).map(h=>`<div class="lifeLine"><b>${h.icon} Year ${h.year}</b><span>${esc(h.text)}</span></div>`).join("")}</section>
 </div>
 <section class="lifeCard"><h3>📰 Recent Life Activity</h3><div class="lifeActivity">${s.activity.slice().reverse().slice(0,16).map(a=>`<div><b>${a.icon}</b><span>Life Day ${a.day+1}: ${esc(a.text)}</span></div>`).join("")||'<div>Life is suspiciously calm.</div>'}</div></section>`;
 bind();}
function bind(){
 $("lifePause")?.addEventListener("click",()=>{s.paused=!s.paused;save();render();pushSnapshot()});document.querySelectorAll("[data-life-speed]").forEach(b=>b.onclick=()=>{s.speed=b.dataset.lifeSpeed;s.paused=false;save();render();pushSnapshot()});
 $("lifeAdvancePeriod")?.addEventListener("click",()=>advanceMinutes(6*60));$("lifeClearWrapped")?.addEventListener("click",()=>{s.wrapped=null;save();render()});
 $("lifeReset")?.addEventListener("click",()=>{if(confirm("Reset ONLY the test Lizzy Life save?")){s=baseState();save();render();pushSnapshot()}});
 $("lifeMiniGame")?.addEventListener("click",()=>{if(!s.job.employed)return;const d=absDay();if(s.job.lastMiniDay===d)return alert("You already played today's optional work mini-game.");s.job.lastMiniDay=d;s.job.careerXP+=10;s.job.performance=clamp(s.job.performance+5,0,100);if(Math.random()<.35)earn(5,"Work mini-game bonus");addActivity("Optional work mini-game completed. Attendance was separate.","🎯");save();render();pushSnapshot()});
 $("lifeSkipWork")?.addEventListener("click",()=>{s.job.skipNextWork=true;addActivity("Next scheduled workday will be deliberately skipped.","🚫");save();render()});
 $("lifeFindJob")?.addEventListener("click",()=>{const ids=Object.keys(JOBS),id=rand(ids),j=JOBS[id];s.job={id,...j,employed:true,missedConsecutive:0,careerXP:0,performance:50,lastMiniDay:-1,skipNextWork:false};s.stats.jobsHeld++;pushHistory(`Started working at ${j.name}.`,"💼");save();render();pushSnapshot()});
 $("lifeRequestLawyer")?.addEventListener("click",()=>{const c=s.legal.slice().reverse().find(x=>x.status==="not_requested");if(!c)return;c.status="requested";s.stats.lawsuits++;addActivity("Requested Mikael Spector legal representation. Awaiting HQ terms.","⚖️");save();render();pushSnapshot()});
 document.querySelectorAll("[data-life-rent]").forEach(b=>b.onclick=()=>{const h=HOMES[b.dataset.lifeRent];s.home={id:b.dataset.lifeRent,...h,owned:false,nextRentAbsDay:absDay()+30};pushHistory(`Moved into ${h.name}.`,"🏠");save();render();pushSnapshot()});
 document.querySelectorAll("[data-life-buy]").forEach(b=>b.onclick=()=>{const h=HOMES[b.dataset.lifeBuy];if(!spend(h.buy,`Bought ${h.name}`))return alert(`You need ${h.buy} LB.`);s.home={id:b.dataset.lifeBuy,...h,owned:true,rent:0};s.stats.properties++;pushHistory(`Bought ${h.name} outright.`,"🏡");save();render();pushSnapshot()});
 $("lifeMortgage")?.addEventListener("click",()=>{const amount=6000,l={id:uid("loan"),amount,purpose:"Home loan / mortgage",status:"pending",requestedLifeMinute:s.lifeMinute};s.loans.push(l);addActivity(`Mortgage application sent to Bank of Micky: ${amount} LB`,"🏦");save();render();pushSnapshot()});
 document.querySelectorAll("[data-life-diet]").forEach(b=>b.onclick=()=>{const d=DIETS[b.dataset.lifeDiet];s.diet={id:b.dataset.lifeDiet,...d,nextRenewAbsDay:absDay()+14,autoRenew:s.diet.autoRenew};addActivity(`Diet changed to ${d.name}.`,d.emoji);save();render();pushSnapshot()});
 $("lifeDietAuto")?.addEventListener("change",e=>{s.diet.autoRenew=e.target.checked;save()});
 document.querySelectorAll("[data-routine]").forEach(i=>i.onchange=()=>{s.routine[i.dataset.routine]=i.checked;save();pushSnapshot()});document.querySelectorAll("[data-routine-select]").forEach(i=>i.onchange=()=>{s.routine[i.dataset.routineSelect]=i.value;save();pushSnapshot()});
 $("lifeSkipDays")?.addEventListener("change",e=>{$("lifeCustomDays").hidden=e.target.value!=="custom"});
 $("lifePreviewSkip")?.addEventListener("click",()=>{const v=$("lifeSkipDays").value;let days=v==="next"?nextEventDays():v==="custom"?Math.max(1,Number($("lifeCustomDays").value)||1):Number(v);if(v==="0"){const p=dateParts(),mins=(22*60)-(p.hour*60+p.minute);return advanceMinutes(mins>0?mins:1440+mins,{autoWorkOverride:$("lifeSkipWorkAuto").checked,stopForProtected:true})}const auto=$("lifeSkipWorkAuto").checked,pr=preview(days,auto);$("lifeSkipPreview").innerHTML=`<b>SKIP ${days} DAY${days===1?"":"S"}?</b><span>Salary expected: +${pr.salary} LB</span><span>Diet renewals: -${pr.diet} LB</span><span>Rent: -${pr.rent} LB</span><span>Loan payments: -${pr.loan} LB</span><span>Workdays: ${pr.workdays}</span><strong>Expected balance: ${Math.round(pr.expected)} LB</strong><button id="lifeDoSkip">SIMULATE ${days} DAY${days===1?"":"S"}</button>`;$("lifeDoSkip").onclick=()=>{if(s.pending.some(x=>x.status==="pending"&&x.kind!=="diet_due"))return alert("A protected decision is waiting. Handle it before a large skip.");advanceMinutes(days*1440,{autoWorkOverride:auto,stopForProtected:true})}});
 $("lifeLoanApply")?.addEventListener("click",()=>{const amount=Math.max(100,Math.floor(Number($("lifeLoanAmount").value)||0));const l={id:uid("loan"),amount,purpose:"Personal loan",status:"pending",requestedLifeMinute:s.lifeMinute};s.loans.push(l);addActivity(`Loan application sent: ${amount} LB`,"🏦");save();render();pushSnapshot()});
 document.querySelectorAll("[data-life-decision]").forEach(b=>b.onclick=()=>{const p=s.pending.find(x=>x.id===b.dataset.id);if(!p)return;const a=b.dataset.lifeDecision;if(p.kind==="mikael_invite"){if(a==="accept"){p.status="accepted";const targetDay=absDay()+p.daysAhead;s.plans.push({id:uid("plan"),inviteId:p.id,title:p.title,withMikael:true,status:"accepted",lifeMinute:targetDay*1440+p.timeMinute});addActivity(`${p.title} added to Life Calendar.`,"❤️")}else if(a==="laugh"){p.status="rejected";s.relationship.mikael.annoyance=clamp(s.relationship.mikael.annoyance+4,0,100);addActivity(`Lizzy laughed at Mikael's invitation. Bold.`,"😂")}else if(a==="later"){addActivity(`Decision postponed: ${p.title}`,"⏳");return}else p.status="rejected"}else{p.status=a==="accept"?"accepted":"resolved";if(p.kind==="recruitment"&&a==="accept")addActivity("Government interview accepted. Storyline pending HQ.","🏛️")}save();render();pushSnapshot()});
}
const win=$("lifeModeWindow"),icon=$("lifeModeIcon"),close=$("lifeModeClose");function open(){win?.classList.remove("hidden");render();syncHQ()}function shut(){win?.classList.add("hidden");save();pushSnapshot()}icon?.addEventListener("click",open);close?.addEventListener("click",shut);
setInterval(()=>{if(document.visibilityState!=="visible"||!win||win.classList.contains("hidden")||s.paused)return;const amount=s.speed==="fast"?60:15;s.simTicks++;advanceMinutes(amount)},1000);
setInterval(syncHQ,5000);window.addEventListener("beforeunload",save);render();syncHQ();
window.LizzyLifeTest={open,getState:()=>JSON.parse(JSON.stringify(s)),advanceDays:d=>advanceMinutes(d*1440)};
})();
