(()=>{
"use strict";
const ROOT=document.getElementById("lifeGameRoot");
const KEY="lizzyLifeTestV1";
const $=(sel,el=document)=>el.querySelector(sel);
const $$=(sel,el=document)=>[...el.querySelectorAll(sel)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const uid=p=>`${p}-${globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`;
const MONTHS=[["January",31],["February",28],["March",31],["April",30],["May",31],["June",30],["July",31],["August",31],["September",30],["October",31],["November",30],["December",31]];
const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const LOCATIONS={home:["🏠","Home","Eat, sleep, recover, watch nonsense or deal with family chaos."],work:["💼","Work","Earn, build your career and survive questionable management."],city:["🏙️","City Centre","Explore, spend Life Bucs and trigger side plots."],cafe:["☕","Café","Coffee, snacks and things you were not meant to overhear."],shops:["🛍️","Shops","Clothes, snacks and completely unnecessary purchases."],gym:["🏋️","Gym","Trade energy for confidence and regret leg day."],park:["🌳","Park","Walk, relax or encounter random nonsense."],restaurant:["🍽️","Restaurant","Spend too much on food because adulthood." ]};
const JOBS={potato:{name:"Potato Industries",salary:28,emoji:"🥔"},paperclips:{name:"Micky's Executive Paperclips",salary:34,emoji:"📎"},bluetooth:{name:"Bluetooth Water Co.",salary:31,emoji:"💧"}};
const HOMES={family:{name:"Mom's House",rent:0,buy:0,emoji:"🏡"},sketchy:{name:"Sketchy Apartment",rent:90,buy:3200,emoji:"🏚️"},decent:{name:"Decent Apartment",rent:200,buy:7000,emoji:"🏢"},luxury:{name:"Luxury Apartment",rent:450,buy:16000,emoji:"🌇"}};
const DIETS={junk:{name:"Junk",cost:40,emoji:"🍟"},balanced:{name:"Balanced",cost:70,emoji:"🥗"},healthy:{name:"Healthy",cost:110,emoji:"🥑"}};
const rand=a=>a[Math.floor(Math.random()*a.length)];
let view="play", active=false, syncBusy=false;
function base(){return{version:4,lifeMinute:480,paused:false,speed:"normal",cash:650,location:"home",needs:{energy:82,hunger:22,fun:62,confidence:55},currentEvent:null,workGame:null,routine:{autoWork:true,autoSleep:true,attendPlans:true},job:{id:"potato",...JOBS.potato,employed:true,missedConsecutive:0,careerXP:0,performance:50,skipNextWork:false},home:{id:"family",...HOMES.family,owned:false},diet:{id:"balanced",...DIETS.balanced,nextRenewAbsDay:14,autoRenew:true},loans:[],legal:[],plans:[],pending:[],history:[{year:1,text:"Lizzy Life began.",icon:"🎮"}],activity:[],relationship:{mikael:{status:"Friends",trust:55,friendship:60,annoyance:4}},stats:{earned:0,spent:0,jobsHeld:1,fired:0,lawsuits:0,lawsuitsWon:0,mikaelDates:0,npcDates:0,bossArguments:0,loansTaken:0,properties:0,junkCravings:0},wrapped:null};}
function hydrate(x){const b=base();if(!x||typeof x!=="object")return b;return{...b,...x,version:4,needs:{...b.needs,...(x.needs||{})},routine:{...b.routine,...(x.routine||{})},job:{...b.job,...(x.job||{})},home:{...b.home,...(x.home||{})},diet:{...b.diet,...(x.diet||{})},relationship:{mikael:{...b.relationship.mikael,...(x.relationship?.mikael||{})}},stats:{...b.stats,...(x.stats||{})},loans:Array.isArray(x.loans)?x.loans:[],legal:Array.isArray(x.legal)?x.legal:[],plans:Array.isArray(x.plans)?x.plans:[],pending:Array.isArray(x.pending)?x.pending:[],history:Array.isArray(x.history)?x.history:b.history,activity:Array.isArray(x.activity)?x.activity:[]};}
function load(){try{return hydrate(JSON.parse(localStorage.getItem(KEY)||"null"))}catch{return base()}}
let s=load();
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}};
function parts(min=s.lifeMinute){const d=Math.floor(min/1440),year=Math.floor(d/365)+1,yd=((d%365)+365)%365;let left=yd,m=0;while(m<11&&left>=MONTHS[m][1])left-=MONTHS[m++][1];const md=((min%1440)+1440)%1440,h=Math.floor(md/60),mm=md%60;return{absDay:d,year,month:m+1,monthName:MONTHS[m][0],day:left+1,dayName:DAYS[((d%7)+7)%7],hour:h,minute:mm,season:m<=1||m===11?"Summer":m<=4?"Autumn":m<=7?"Winter":"Spring",period:h<12?"Morning":h<17?"Afternoon":h<22?"Evening":"Night"};}
const absDay=()=>Math.floor(s.lifeMinute/1440);
const dateText=()=>{const p=parts();return `${p.dayName}, ${p.day} ${p.monthName} — Year ${p.year} · ${String(p.hour).padStart(2,"0")}:${String(p.minute).padStart(2,"0")} · ${p.season}`};
function activity(text,icon="•"){s.activity.push({day:absDay(),text,icon});s.activity=s.activity.slice(-120)}
function history(text,icon="📌"){s.history.push({year:parts().year,text,icon});s.history=s.history.slice(-160)}
function spend(n,why){n=Math.round(Number(n)||0);if(s.cash<n)return false;s.cash-=n;s.stats.spent+=n;activity(`-${n} LB · ${why}`,"💸");return true}
function earn(n,why){n=Math.round(Number(n)||0);s.cash+=n;s.stats.earned+=n;activity(`+${n} LB · ${why}`,"💰")}
const workday=d=>((d%7)+7)%7<5;
function fire(reason){if(!s.job.employed)return;s.job.employed=false;s.job.missedConsecutive=0;s.stats.fired++;s.legal.push({id:uid("case"),reason,status:"not_requested",createdLifeMinute:s.lifeMinute});s.currentEvent={emoji:"🔥",title:"YOU HAVE BEEN FIRED",text:reason,choices:[["⚖️ Hire Mikael Spector","lawyer"],["😡 Insult Former Boss","insultboss"],["📝 Find Another Job","findjob"],["🛋️ Become Unemployed","close"]]};activity(`FIRED: ${reason}`,"🔥");history(`Fired from ${s.job.name}: ${reason}`,"🔥")}
function daily(day,autoWorkOverride=null){const aw=autoWorkOverride==null?s.routine.autoWork:autoWorkOverride;if(workday(day)&&s.job.employed){const miss=s.job.skipNextWork||!aw;s.job.skipNextWork=false;if(miss){s.job.missedConsecutive++;activity(`Missed work. (${s.job.missedConsecutive}/3)`,"🚫");if(s.job.missedConsecutive>=3)fire("Three consecutive missed workdays. Your boss finally noticed.")}else{s.job.missedConsecutive=0;earn(s.job.salary,`${s.job.name} salary`);s.job.performance=clamp(s.job.performance+1);}}
 if(day>=s.diet.nextRenewAbsDay){if(s.diet.autoRenew&&spend(s.diet.cost,`${s.diet.name} groceries`)){s.diet.nextRenewAbsDay=day+14}else{s.pending.push({id:uid("diet"),kind:"diet_due",title:"Groceries need attention",status:"pending"});s.diet.nextRenewAbsDay=day+1}}
 const p=parts(day*1440+720);if(!s.home.owned&&s.home.rent>0&&p.day===1)spend(s.home.rent,`${s.home.name} rent`);
 for(const l of s.loans.filter(x=>x.status==="active"&&day>=x.nextPaymentDay)){const pay=Math.min(l.payment,l.balance);if(spend(pay,"Bank of Micky loan payment")){l.balance-=pay;l.nextPaymentDay=day+30;if(l.balance<=0)l.status="paid"}}
 for(const pl of s.plans.filter(x=>x.status==="accepted"&&Math.floor(x.lifeMinute/1440)===day)){if(s.routine.attendPlans!==false){pl.status="attended";if(pl.withMikael){s.relationship.mikael.trust=clamp(s.relationship.mikael.trust+3);s.relationship.mikael.friendship=clamp(s.relationship.mikael.friendship+4);s.stats.mikaelDates++}activity(`Attended: ${pl.title}`,"❤️")}else{pl.status="missed";if(pl.withMikael){s.relationship.mikael.trust=clamp(s.relationship.mikael.trust-10);s.relationship.mikael.annoyance=clamp(s.relationship.mikael.annoyance+15)}activity(`Missed plan: ${pl.title}`,"😬")}}
 s.needs.hunger=clamp(s.needs.hunger+12);s.needs.energy=clamp(s.needs.energy-8);s.needs.fun=clamp(s.needs.fun-3);
}
function advance(mins,{autoWork=null,stopProtected=false,draw=true,sync=true}={}){mins=Math.max(0,Math.floor(mins));let remain=mins;while(remain>0){const d=absDay(),midnight=(d+1)*1440,step=Math.min(remain,midnight-s.lifeMinute);s.lifeMinute+=step;remain-=step;if(s.lifeMinute===midnight){daily(absDay(),autoWork);if(stopProtected&&s.pending.some(x=>x.status==="pending"&&x.kind!=="diet_due"))break}}save();if(draw)render();if(sync)pushSnapshot();}
function maybeEvent(force=false){if(s.currentEvent||s.workGame||(!force&&Math.random()>.24))return;const pool=[{emoji:"💸",title:"Sefura Has Appeared",text:"Sefura needs 20 LB for something described only as 'important'.",choices:[["Give 20 LB","sefura_pay"],["Absolutely not","sefura_no"]]},{emoji:"📱",title:"Mikael Sent a Meme",text:"It is objectively terrible. Unfortunately it is also quite funny.",choices:[["😂 Laugh","meme_laugh"],["🔥 Roast him","meme_roast"],["Leave on read","meme_ignore"]]},{emoji:"👛",title:"You Found a Wallet",text:"There is 30 LB inside and an ID card.",choices:[["Return it","wallet_return"],["Keep the 30 LB","wallet_keep"]]},{emoji:"🎟️",title:"Suspicious Free Ticket",text:"Someone outside the city centre has offered you a free ticket to a mystery event.",choices:[["Take it","ticket_take"],["No thanks","ticket_no"]]}];s.currentEvent=rand(pool);save()}
function resolveEvent(a){const r=s.relationship.mikael,n=s.needs;switch(a){case"sefura_pay":if(!spend(20,"Sefura emergency"))return alert("You need 20 LB.");break;case"sefura_no":n.confidence+=2;break;case"meme_laugh":r.friendship+=3;n.fun+=6;break;case"meme_roast":r.friendship+=1;r.annoyance+=2;n.fun+=8;break;case"meme_ignore":r.annoyance+=3;break;case"wallet_return":n.confidence+=8;activity("Returned the lost wallet.","😇");break;case"wallet_keep":earn(30,"Found wallet money");n.confidence-=3;break;case"ticket_take":n.fun+=8;activity("Accepted a suspicious free ticket.","🎟️");break;case"ticket_no":n.confidence+=2;break;case"lawyer":{const c=[...s.legal].reverse().find(x=>x.status==="not_requested");if(c){c.status="requested";s.stats.lawsuits++;activity("Requested Mikael Spector.","⚖️")}}break;case"insultboss":s.stats.bossArguments++;n.fun+=8;break;case"findjob":findJob();break}Object.keys(n).forEach(k=>n[k]=clamp(n[k]));s.currentEvent=null;save();render();pushSnapshot()}
function findJob(){const opts=Object.entries(JOBS).filter(([id])=>id!==s.job.id),[id,j]=rand(opts);s.job={id,...j,employed:true,missedConsecutive:0,careerXP:0,performance:50,skipNextWork:false};s.stats.jobsHeld++;activity(`Started a new job at ${j.name}.`,j.emoji);history(`Joined ${j.name}.`,j.emoji)}
function workStart(){if(!s.job.employed)return alert("You do not have a job.");s.location="work";s.workGame={round:1,score:0,target:rand(["URGENT","POTATO","CONFIDENTIAL","TOTALLY NORMAL","DO NOT OPEN"]),pool:["URGENT","POTATO","CONFIDENTIAL","TOTALLY NORMAL","DO NOT OPEN"]};save();render()}
function workChoice(label){const g=s.workGame;if(!g)return;if(label===g.target)g.score++;if(g.round>=5){const score=g.score;s.job.careerXP+=score*4;s.job.performance=clamp(s.job.performance+score*2);if(score>=4)earn(8+score,"Work challenge bonus");activity(`Work challenge: ${score}/5 correct.`,"🎯");s.workGame=null;advance(90,{draw:false});maybeEvent();save();render();pushSnapshot();return}g.round++;g.target=rand(g.pool);save();render()}
function act(id){const n=s.needs,r=s.relationship.mikael;let mins=30,msg="";const pay=(x,w)=>{if(!spend(x,w)){alert(`You need ${x} LB.`);return false}return true};switch(id){case"eat_home":n.hunger-=35;n.energy+=5;mins=35;msg="Ate at home.";break;case"shower":n.confidence+=9;mins=25;msg="Had a shower.";break;case"tv":n.fun+=18;n.energy-=4;mins=75;msg="Watched TV.";break;case"text_mikael":r.friendship+=2;n.fun+=5;mins=20;msg="Texted Mikael.";break;case"family":n.fun+=8;mins=60;msg="Spent time with family.";maybeEvent(true);break;case"sleep":{const p=parts(),now=p.hour*60+p.minute;mins=now<420?420-now:1440-now+420;n.energy=100;n.hunger+=15;msg="Slept until morning.";break}case"work_game":return workStart();case"extra_work":s.job.careerXP+=8;s.job.performance=clamp(s.job.performance+4);n.energy-=12;mins=120;msg="Did extra work.";break;case"office_coffee":n.energy+=12;mins=20;msg="Drank office coffee.";break;case"skip_work":s.job.skipNextWork=true;mins=5;msg="Next workday will be skipped.";break;case"explore":n.fun+=10;n.energy-=5;mins=70;msg="Explored the city.";maybeEvent(true);break;case"messages":n.fun+=4;mins=20;msg="Checked messages.";break;case"random":mins=45;msg="Did something random.";maybeEvent(true);break;case"coffee":if(!pay(12,"Café coffee"))return;n.energy+=18;n.fun+=5;mins=30;msg="Bought coffee.";break;case"cafe_snack":if(!pay(22,"Café snack"))return;n.hunger-=25;n.fun+=7;mins=45;msg="Had coffee and a snack.";break;case"eavesdrop":n.fun+=10;mins=35;msg="Eavesdropped irresponsibly.";maybeEvent(true);break;case"outfit":if(!pay(75,"New outfit"))return;n.confidence+=20;n.fun+=8;mins=75;msg="Bought an outfit.";break;case"shop_snack":if(!pay(10,"Shop snack"))return;n.hunger-=20;mins=20;msg="Bought a snack.";break;case"browse":n.fun+=6;mins=60;msg="Window-shopped.";break;case"cardio":n.energy-=18;n.hunger+=12;n.confidence+=10;mins=75;msg="Did cardio.";break;case"strength":n.energy-=22;n.hunger+=15;n.confidence+=13;mins=90;msg="Did strength training.";break;case"stretch":n.energy+=8;n.confidence+=4;mins=45;msg="Stretched and recovered.";break;case"walk":n.energy+=4;n.fun+=10;mins=60;msg="Walked in the park.";maybeEvent();break;case"relax":n.energy+=12;n.fun+=7;mins=60;msg="Relaxed in the park.";break;case"call_mikael":r.friendship+=4;r.trust+=2;n.fun+=8;mins=35;msg="Called Mikael.";break;case"meal":if(!pay(35,"Restaurant meal"))return;n.hunger-=55;n.fun+=10;mins=80;msg="Had a proper meal.";break;case"dessert":if(!pay(18,"Dessert"))return;n.hunger-=20;n.fun+=12;mins=45;msg="Bought dessert.";break;case"drink":if(!pay(9,"Drink"))return;n.hunger-=5;n.fun+=4;mins=30;msg="Had a drink.";break;default:return}Object.keys(n).forEach(k=>n[k]=clamp(n[k]));activity(msg,LOCATIONS[s.location]?.[0]||"🎮");advance(mins,{draw:false});if(!s.currentEvent)maybeEvent();save();render();pushSnapshot()}
function travel(id){if(!LOCATIONS[id]||id===s.location)return;s.location=id;activity(`Travelled to ${LOCATIONS[id][1]}.`,LOCATIONS[id][0]);advance(20,{draw:false});maybeEvent();save();render();pushSnapshot()}
function worker(){return String(window.LIZZY_TELEGRAM_WORKER_URL||"").trim()}
async function api(action,body={}){const u=worker();if(!u)throw new Error("Test Worker not configured");const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
function publicState(){return{lifeMinute:s.lifeMinute,date:dateText(),dateParts:parts(),paused:s.paused,speed:s.speed,cash:s.cash,location:s.location,needs:s.needs,job:s.job,home:s.home,diet:s.diet,routine:s.routine,loans:s.loans,legal:s.legal,plans:s.plans,pending:s.pending,relationship:s.relationship,stats:s.stats,activity:s.activity.slice(-30),history:s.history.slice(-40),wrapped:s.wrapped}}
async function pushSnapshot(){if(syncBusy)return;syncBusy=true;try{await api("life_snapshot_put",{snapshot:publicState()})}catch{}finally{syncBusy=false}}
async function syncHQ(){const u=worker();if(!u)return;try{const r=await fetch(u+`?action=life_queue`,{cache:"no-store"});const d=await r.json().catch(()=>({})),cmds=d.commands||[],ids=[];for(const c of cmds){if(c.kind==="life_invite"){if(!s.pending.some(x=>x.id===c.id))s.pending.push({id:c.id,kind:"mikael_invite",title:c.title||"Plan with Mikael",detail:c.detail||"",daysAhead:Math.max(1,Number(c.daysAhead)||1),timeMinute:Number(c.timeMinute)||1140,status:"pending",withMikael:true})}else if(c.kind==="recruitment"){if(!s.pending.some(x=>x.id===c.id))s.pending.push({id:c.id,kind:"recruitment",source:c.source==="office"?"office":"government",recruiter:c.recruiter||(c.source==="office"?"Michael Scott":"President Mikael"),organization:c.organization||(c.source==="office"?"The Office":"Government"),title:c.title||"Recruitment",detail:c.detail||"",status:"pending"})}else if(c.kind==="loan_decision"){const l=s.loans.find(x=>x.id===c.requestId);if(l){if(c.decision==="approve"){l.status="active";l.payment=Math.max(1,Number(c.payment)||Math.ceil(l.amount/6));l.balance=l.amount;l.nextPaymentDay=absDay()+30;earn(l.amount,"Bank of Micky loan approved");s.stats.loansTaken++}else l.status="rejected"}}else if(c.kind==="legal_decision"){const l=s.legal.find(x=>x.id===c.requestId);if(l){l.status=c.decision==="accept"?"represented":"rejected";l.terms=c.terms||null}}ids.push(c.id)}if(ids.length){await api("life_ack",{ids});save();render()}await pushSnapshot()}catch{}}
function pendingHTML(){const ps=s.pending.filter(x=>x.status==="pending");if(!ps.length)return'<div class="empty">No protected decisions waiting.</div>';return ps.map(p=>`<div class="pending"><b>${p.kind==="recruitment"?(p.source==="office"?"📎 THE OFFICE · ":"🏛️ GOVERNMENT · "):""}${esc(p.title)}</b>${p.kind==="recruitment"?`<small>${esc(p.recruiter||"")} · ${esc(p.organization||"")}</small>`:""}<p>${esc(p.detail||"")}</p><div class="row">${p.kind==="mikael_invite"?`<button data-decision="accept" data-id="${esc(p.id)}">❤️ Accept</button><button data-decision="reject" data-id="${esc(p.id)}">Reject</button><button data-decision="laugh" data-id="${esc(p.id)}">😂 Laugh</button>`:`<button data-decision="accept" data-id="${esc(p.id)}">${p.source==="office"?"📎 Attend Michael Scott Interview":"🏛️ Attend Government Interview"}</button><button data-decision="reject" data-id="${esc(p.id)}">Decline</button>`}</div></div>`).join("")}
function decision(id,a){const p=s.pending.find(x=>x.id===id);if(!p)return;if(p.kind==="mikael_invite"){if(a==="accept"){p.status="accepted";const day=absDay()+p.daysAhead;s.plans.push({id:uid("plan"),inviteId:p.id,title:p.title,withMikael:true,status:"accepted",lifeMinute:day*1440+p.timeMinute});activity(`${p.title} added to calendar.`,"❤️")}else{p.status="rejected";if(a==="laugh")s.relationship.mikael.annoyance=clamp(s.relationship.mikael.annoyance+4)}}else{p.status=a==="accept"?"accepted":"rejected";if(p.kind==="recruitment"&&a==="accept"){activity(p.source==="office"?"Accepted Michael Scott's interview.":"Accepted President Mikael's Government interview.",p.source==="office"?"📎":"🏛️");history(p.source==="office"?"Accepted a Michael Scott interview for The Office.":"Accepted a Government interview with President Mikael.",p.source==="office"?"📎":"🏛️")}}save();render();pushSnapshot()}
function need(label,v){v=clamp(Math.round(v));return `<div class="need ${v<25?"bad":""}">${label}<div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`}
function actions(){const a={home:[["🍳 Eat at Home","eat_home"],["🚿 Shower","shower"],["📺 Watch TV","tv"],["💬 Text Mikael","text_mikael"],["👨‍👩‍👧 Family Time","family"],["😴 Sleep","sleep"]],work:[["🎯 Start Work Challenge","work_game"],["🗂️ Do Extra Work","extra_work"],["☕ Office Coffee","office_coffee"],["🚫 Skip Next Workday","skip_work"]],city:[["🚶 Explore City","explore"],["📱 Check Messages","messages"],["🎲 Do Something Random","random"]],cafe:[["☕ Coffee · 12 LB","coffee"],["🥐 Coffee + Snack · 22 LB","cafe_snack"],["👂 Eavesdrop","eavesdrop"]],shops:[["👗 Outfit · 75 LB","outfit"],["🍫 Snack · 10 LB","shop_snack"],["🛍️ Window Shop","browse"]],gym:[["🏃 Cardio","cardio"],["🏋️ Strength Workout","strength"],["🧘 Stretch","stretch"]],park:[["🚶 Walk","walk"],["🪑 Relax","relax"],["📞 Call Mikael","call_mikael"]],restaurant:[["🍝 Meal · 35 LB","meal"],["🍰 Dessert · 18 LB","dessert"],["🥤 Drink · 9 LB","drink"]]};return(a[s.location]||[]).map(x=>`<button data-act="${x[1]}">${x[0]}</button>`).join("")}
function eventHTML(){if(s.workGame){const g=s.workGame;return `<div class="event work"><div class="emoji">🎯</div><div><small>WORK CHALLENGE · ROUND ${g.round}/5</small><h3>Click: ${esc(g.target)}</h3><p>Correct answers improve Career XP and performance.</p><div class="choice">${g.pool.map(x=>`<button data-work="${esc(x)}">${esc(x)}</button>`).join("")}</div></div></div>`}if(!s.currentEvent)return"";const e=s.currentEvent;return `<div class="event"><div class="emoji">${e.emoji}</div><div><small>RANDOM LIFE EVENT</small><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p><div class="choice">${e.choices.map(x=>`<button data-event="${x[1]}">${x[0]}</button>`).join("")}</div></div></div>`}
function playHTML(){const l=LOCATIONS[s.location]||LOCATIONS.home,p=parts();return `<div class="playgrid"><section class="scene"><div class="scenehead"><div class="sceneemoji">${l[0]}</div><div><small>${p.period.toUpperCase()} · ${p.dayName.toUpperCase()}</small><h2>${l[1]}</h2><p>${l[2]}</p></div></div><div class="needs">${need("⚡ Energy",s.needs.energy)}${need("🍽️ Fullness",100-s.needs.hunger)}${need("🎉 Fun",s.needs.fun)}${need("✨ Confidence",s.needs.confidence)}</div><div class="actionhead"><b>What do you want to do?</b><span>Actions advance only Life Time.</span></div><div class="actions">${actions()}</div></section><aside class="side"><div class="card"><h3>📍 Go Somewhere</h3><div class="travel">${Object.entries(LOCATIONS).map(([id,l])=>`<button class="${id===s.location?"on":""}" data-travel="${id}">${l[0]} ${l[1]}</button>`).join("")}</div></div>${s.pending.some(x=>x.status==="pending")?`<div class="card"><h3>🛑 Decisions Waiting</h3>${pendingHTML()}</div>`:""}<div class="card"><h3>🎯 Current Goal</h3><p>${s.job.employed?`Survive <b>${esc(s.job.name)}</b>, build XP and don't get fired.`:"Find a job or embrace unemployment."}</p><p><b>${Math.round(s.cash)} LB</b> available.</p></div></aside></div>${eventHTML()}<div class="card activity"><h3>📰 What just happened</h3>${s.activity.slice(-7).reverse().map(a=>`<div class="line"><b>${a.icon} Day ${a.day+1}</b><span>${esc(a.text)}</span></div>`).join("")||'<div class="empty">Start playing and your story appears here.</div>'}</div>`}
function manageHTML(){return `<div class="grid"><div class="card"><h3>💼 Career</h3><p>${s.job.employed?`${s.job.emoji} <b>${esc(s.job.name)}</b> · ${s.job.salary} LB/workday`:`🛋️ <b>Unemployed</b>`}</p><small>Missed: ${s.job.missedConsecutive}/3 · XP ${s.job.careerXP} · Performance ${s.job.performance}%</small><div class="row"><button data-manage="work">🎯 Work Challenge</button><button data-manage="skipwork">🚫 Skip Next Workday</button>${!s.job.employed?'<button data-manage="findjob">📝 Find Job</button>':""}${!s.job.employed&&s.legal.some(x=>x.status==="not_requested")?'<button data-manage="lawyer">⚖️ Mikael Spector</button>':""}</div></div><div class="card"><h3>🏠 Housing</h3><p>${s.home.emoji} <b>${esc(s.home.name)}</b> · ${s.home.owned?"OWNED":s.home.rent?`${s.home.rent} LB/month`:"Living at home"}</p><div class="row">${Object.entries(HOMES).filter(([id])=>id!=="family").map(([id,h])=>`<button data-rent="${id}">Rent ${h.name}</button><button data-buy="${id}">Buy ${h.buy} LB</button>`).join("")}</div><button data-manage="mortgage">🏦 Ask Bank of Micky for Mortgage</button></div><div class="card"><h3>🛒 Diet</h3><p>${s.diet.emoji} ${s.diet.name} · ${s.diet.cost} LB / 14 days</p><div class="row">${Object.entries(DIETS).map(([id,d])=>`<button data-diet="${id}">${d.emoji} ${d.name}</button>`).join("")}</div><label><input id="dietAuto" type="checkbox" ${s.diet.autoRenew?"checked":""}> Auto-renew</label></div><div class="card"><h3>❤️ Mikael</h3><p>Status: <b>${esc(s.relationship.mikael.status)}</b></p><small>Trust ${s.relationship.mikael.trust} · Friendship ${s.relationship.mikael.friendship} · Annoyance ${s.relationship.mikael.annoyance}</small></div></div><div class="grid3 grid" style="margin-top:10px"><div class="card"><h3>⏩ Skip Time</h3><div class="row"><select id="skipDays"><option value="1">1 Day</option><option value="3">3 Days</option><option value="7">1 Week</option><option value="14">14 Days</option><option value="30">1 Month</option><option value="90">3 Months</option><option value="180">6 Months</option><option value="365">1 Life Year</option></select><label><input id="skipAutoWork" type="checkbox" checked> Auto-work</label><button data-manage="skip">Simulate</button></div></div><div class="card"><h3>🏦 Bank of Micky</h3><div class="row"><input id="loanAmount" type="number" value="2500" min="100" step="100"><button data-manage="loan">Request Loan</button></div><small>${s.loans.length?`${s.loans.length} loan request(s)/loan(s) in history.`:"No loans yet."}</small></div><div class="card"><h3>🧠 Auto Routine</h3><label><input data-routine="autoWork" type="checkbox" ${s.routine.autoWork?"checked":""}> Auto-attend work</label><br><label><input data-routine="attendPlans" type="checkbox" ${s.routine.attendPlans?"checked":""}> Attend scheduled plans</label></div></div>`}
function storyHTML(){const upcoming=s.plans.filter(x=>x.status==="accepted"&&x.lifeMinute>s.lifeMinute).sort((a,b)=>a.lifeMinute-b.lifeMinute);return `<div class="grid3 grid"><div class="card"><h3>🛑 Protected Decisions</h3>${pendingHTML()}</div><div class="card"><h3>📅 Upcoming Plans</h3>${upcoming.map(x=>`<div class="line"><b>${esc(x.title)}</b><span>${esc((()=>{const p=parts(x.lifeMinute);return `${p.day} ${p.monthName} Y${p.year} ${String(p.hour).padStart(2,"0")}:${String(p.minute).padStart(2,"0")}`})())}</span></div>`).join("")||'<div class="empty">Nothing scheduled.</div>'}</div><div class="card"><h3>📜 Life History</h3>${s.history.slice(-15).reverse().map(x=>`<div class="line"><b>${x.icon} Y${x.year}</b><span>${esc(x.text)}</span></div>`).join("")}</div></div>`}
function render(){const p=parts(),l=LOCATIONS[s.location]||LOCATIONS.home;ROOT.innerHTML=`<div class="shell"><div class="hero"><div><small>LIFE TIME · ZERO REAL-WORLD CATCH-UP</small><h1>🎮 Lizzy Life</h1><strong>${esc(dateText())}</strong><span class="sub">${p.period} · ${l[1]} · <span class="statusdot ${active?"":"off"}"></span>${active?"Life clock active":"Life clock frozen"}</span></div><div class="cash">${Math.round(s.cash)}<small>LIFE BUCS</small></div></div><div class="toolbar"><div class="tabs"><button data-view="play" class="${view==="play"?"on":""}">🎮 Play</button><button data-view="manage" class="${view==="manage"?"on":""}">🧾 Manage Life</button><button data-view="story" class="${view==="story"?"on":""}">📅 Story & Calendar</button></div><button data-top="pause">${s.paused?"▶ Resume":"⏸ Pause"}</button><button data-top="normal" class="${s.speed==="normal"?"on":""}">▶ Normal</button><button data-top="fast" class="${s.speed==="fast"?"on":""}">▶▶ Fast</button><button class="danger" data-top="reset">Reset Test</button></div><div class="notice"><b>Virtual-time rule:</b> closing this Life screen freezes it. No matter whether you return in 10 minutes or 3 months, no offline Life time is added.</div>${s.wrapped?`<div class="wrapped"><button data-top="clearwrap">Close</button><b>🎆 YEAR ${s.wrapped.year} WRAPPED</b></div>`:""}${view==="play"?playHTML():view==="manage"?manageHTML():storyHTML()}<div class="testbanner">TEST BUILD · TestHQ sync ${worker()?"connected":"not configured"}</div></div>`}
ROOT.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return}if(b.dataset.travel){travel(b.dataset.travel);return}if(b.dataset.act){act(b.dataset.act);return}if(b.dataset.event){resolveEvent(b.dataset.event);return}if(b.dataset.work){workChoice(b.dataset.work);return}if(b.dataset.decision){decision(b.dataset.id,b.dataset.decision);return}if(b.dataset.top){if(b.dataset.top==="pause")s.paused=!s.paused;if(b.dataset.top==="normal"){s.speed="normal";s.paused=false}if(b.dataset.top==="fast"){s.speed="fast";s.paused=false}if(b.dataset.top==="clearwrap")s.wrapped=null;if(b.dataset.top==="reset"&&confirm("Reset only the TEST Lizzy Life save?"))s=base();save();render();pushSnapshot();return}if(b.dataset.manage){const a=b.dataset.manage;if(a==="work")workStart();if(a==="skipwork"){s.job.skipNextWork=true;activity("Next workday will be skipped.","🚫")}if(a==="findjob")findJob();if(a==="lawyer"){const c=[...s.legal].reverse().find(x=>x.status==="not_requested");if(c){c.status="requested";s.stats.lawsuits++;activity("Requested Mikael Spector.","⚖️")}}if(a==="mortgage"){s.loans.push({id:uid("loan"),amount:6000,purpose:"Home loan / mortgage",status:"pending",requestedLifeMinute:s.lifeMinute});activity("Mortgage application sent.","🏦")}if(a==="loan"){const amt=Math.max(100,Math.floor(Number($("#loanAmount")?.value)||2500));s.loans.push({id:uid("loan"),amount:amt,purpose:"Personal loan",status:"pending",requestedLifeMinute:s.lifeMinute});activity(`Loan application sent: ${amt} LB`,"🏦")}if(a==="skip"){const days=Math.max(1,Number($("#skipDays")?.value)||1),auto=$("#skipAutoWork")?.checked!==false;if(s.pending.some(x=>x.status==="pending"&&x.kind!=="diet_due"))return alert("Handle the protected decision first.");advance(days*1440,{autoWork:auto,stopProtected:true,draw:false})}save();render();pushSnapshot();return}if(b.dataset.rent){const h=HOMES[b.dataset.rent];s.home={id:b.dataset.rent,...h,owned:false};activity(`Moved into ${h.name}.`,"🏠");save();render();pushSnapshot();return}if(b.dataset.buy){const h=HOMES[b.dataset.buy];if(!spend(h.buy,`Bought ${h.name}`))return alert(`You need ${h.buy} LB.`);s.home={id:b.dataset.buy,...h,owned:true,rent:0};s.stats.properties++;history(`Bought ${h.name}.`,"🏡");save();render();pushSnapshot();return}if(b.dataset.diet){const d=DIETS[b.dataset.diet];s.diet={id:b.dataset.diet,...d,nextRenewAbsDay:absDay()+14,autoRenew:s.diet.autoRenew};save();render();pushSnapshot();return}});
ROOT.addEventListener("change",e=>{if(e.target.id==="dietAuto"){s.diet.autoRenew=e.target.checked;save();pushSnapshot()}if(e.target.dataset.routine){s.routine[e.target.dataset.routine]=e.target.checked;save();pushSnapshot()}});
window.addEventListener("message",e=>{if(e.origin!==location.origin)return;if(e.data?.type==="lizzy-life-active"){active=!!e.data.active;render()}});
document.addEventListener("visibilitychange",()=>{if(document.visibilityState!=="visible")active=false;render()});
let ticks=0;setInterval(()=>{if(!active||document.visibilityState!=="visible"||s.paused||view!=="play"||s.currentEvent||s.workGame)return;advance(s.speed==="fast"?45:10,{draw:false,sync:false});ticks++;if(ticks%3===0){save();render();pushSnapshot()}},1000);
setInterval(syncHQ,5000);
window.addEventListener("beforeunload",save);
render();syncHQ();pushSnapshot();
})();
