(()=>{'use strict';
const WORKER_KEY='lizzyos_test_worker_url_v1',WALLET='lizzyMickyBucsTESTV1',OWNED='lizzyRadioOwnedTESTV1',CLAIMED='lizzyRadioClaimedChallengesTESTV1';
const stations={propaganda:{name:'Propaganda Radio',price:0},lizzy:{name:'Lizzy Radio',price:200},presidential:{name:'Presidential Radio',price:250}};
let state=null,station=localStorage.getItem('lizzyRadioStation')||'propaganda',audio=new Audio(),playing=false,autoMode=false,recorder=null,chunks=[],voiceData='';
let rotation={first:true,tracksSinceAd:0,lastId:''},livePc=null,liveSession='',liveAudio=new Audio(),resumeAfterLive=false,liveConnecting=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function workerUrl(){let w=String(window.LIZZY_TELEGRAM_WORKER_URL||localStorage.getItem(WORKER_KEY)||'').trim();if(w&&!w.endsWith('/'))w+='/';return w}
function requireWorker(){const w=workerUrl();if(!w)throw Error('TEST Worker not connected. Click the 🧪 TEST SITE badge and enter the Test Worker URL.');return w}
async function readJson(r){const ct=(r.headers.get('content-type')||'').toLowerCase(),text=await r.text();if(!ct.includes('application/json'))throw Error(text.includes('LizzyOS Notification System: ONLINE')?'Test Worker is online, but the Radio v2 routes are missing. Upload the updated TEST worker file.':'Worker returned non-JSON data. Check the TEST Worker connection.');try{return JSON.parse(text)}catch{throw Error('Invalid JSON returned by the TEST Worker.')}}
async function api(body){const w=requireWorker(),r=await fetch(w,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'}),d=await readJson(r);if(!r.ok||d.success===false)throw Error(d.error||'Radio request failed');return d}
function audioSrc(x){if(!x)return'';if(x.audioKey)return workerUrl()+'?radioAudio='+encodeURIComponent(x.audioKey);return x.url||x.audioUrl||''}
const wallet=()=>Math.max(0,Number(localStorage.getItem(WALLET)||0)),setWallet=n=>{localStorage.setItem(WALLET,String(Math.max(0,Math.floor(n))));window.dispatchEvent(new Event('lizzyStoreRefresh'))};
const owned=()=>{try{return JSON.parse(localStorage.getItem(OWNED)||'{}')}catch{return{}}},saveOwned=o=>localStorage.setItem(OWNED,JSON.stringify(o));
function has(id){return stations[id].price===0||!!owned()[id]}
function setStatus(t){const x=$('#rrStatus');if(x)x.textContent=t}
function minutes(t){const m=String(t||'').match(/^(\d{2}):(\d{2})$/);return m?Number(m[1])*60+Number(m[2]):-1}
function fallbackShow(id){const h=new Date().getHours(),shows={propaganda:h<12?['Good Morning, Glorious Nation','Outrageously official morning propaganda.']:h<17?['Department of Statistics','Numbers approved by the government.']:h<21?['State News Tonight','The nation’s least balanced news hour.']:['The Glorious Evening Report','A calm end to another flawless Presidential day.'],lizzy:h<12?['The Lizzy Morning Show','Cute stories, fun news and today’s challenge.']:h<17?['Lizzy & Mikael Lunch Break','Stories, dedications and song requests.']:h<21?['Cute News at Five','The cutest and funniest developments from LizzyOS.']:['Late Night Lizzy','Memories, messages and softer radio.'],presidential:h<12?['Presidential Morning Address','From the President’s desk.']:h<17?['Bank of Micky Market Update','Markets, companies and economic nonsense.']:h<21?['State of LizzyOS','Features, systems and Presidential commentary.']:['From the President’s Desk','Evening thoughts, audio and selected songs.']};const x=shows[id]||[stations[id].name,'On air'];return{title:x[0],subtitle:x[1]}}
function scheduledShow(id){const xs=(state?.schedule||[]).filter(x=>x.station===id&&minutes(x.time)>=0).slice().sort((a,b)=>minutes(a.time)-minutes(b.time));if(!xs.length)return fallbackShow(id);const now=new Date().getHours()*60+new Date().getMinutes();let picked=xs.filter(x=>minutes(x.time)<=now).pop()||xs[xs.length-1];return{title:picked.title||stations[id].name,subtitle:picked.text||`Scheduled for ${picked.time}`,text:picked.text||'',scheduled:true,time:picked.time}}
function current(){const live=state?.live;if(live?.active&&live.station===station)return{title:'🔴 '+(live.headline||'LIVE FROM HQ'),subtitle:'Live from Mikael HQ right now.',live:true};const n=state?.stations?.[station]?.now||{};if(n.createdAt&&n.createdAt!=='seed'){const age=Date.now()-new Date(n.createdAt).getTime();if(Number.isFinite(age)&&age<2*60*60*1000)return n}return scheduledShow(station)}
async function pull(){try{const w=requireWorker(),u=new URL(w);u.searchParams.set('radioState','1');const r=await fetch(u.toString(),{cache:'no-store'}),d=await readJson(r);if(!r.ok||d.success===false)throw Error(d.error||'Radio state unavailable');state=d.state;render();checkRewards();await ensureLive();const count=(state?.tracks||[]).filter(x=>(x.stations||[]).includes(station)).length;setStatus(`🧪 TEST Worker connected · ${count} station track${count===1?'':'s'} loaded.`)}catch(e){setStatus('TEST Radio offline: '+e.message)}}
function mediaPool(kind){const xs=kind==='track'?state?.tracks:kind==='ad'?state?.ads:state?.jingles;return (xs||[]).filter(x=>{if(!audioSrc(x))return false;if(kind==='track'||kind==='ad')return (x.stations||[]).includes(station)&&x.enabled!==false;return x.station===station})}
function weightedAd(xs){const bag=[];for(const x of xs){const n=x.frequency==='frequent'?4:x.frequency==='rare'?1:2;for(let i=0;i<n;i++)bag.push(x)}return bag[Math.floor(Math.random()*bag.length)]}
function randomDifferent(xs){if(!xs.length)return null;const ys=xs.filter(x=>String(x.id)!==rotation.lastId);return (ys.length?ys:xs)[Math.floor(Math.random()*(ys.length?ys:xs).length)]}
function nextRotationItem(){const tracks=mediaPool('track'),ads=mediaPool('ad'),jingles=mediaPool('jingle');if(rotation.first){rotation.first=false;const opener=jingles.filter(x=>x.kind==='station');if(opener.length)return{...randomDifferent(opener),mediaKind:'jingle'}}if(rotation.tracksSinceAd>=3&&ads.length){rotation.tracksSinceAd=0;return{...weightedAd(ads),mediaKind:'ad'}}if(tracks.length){rotation.tracksSinceAd++;if(jingles.length&&rotation.tracksSinceAd>1&&Math.random()<.16){const transition=jingles.filter(x=>x.kind==='show');if(transition.length)return{...randomDifferent(transition),mediaKind:'jingle'}}return{...randomDifferent(tracks),mediaKind:'track'}}if(ads.length)return{...weightedAd(ads),mediaKind:'ad'};if(jingles.length)return{...randomDifferent(jingles),mediaKind:'jingle'};return null}
function showMedia(m){if(!m)return;rotation.lastId=String(m.id||'');$('#rrTitle').textContent=(m.mediaKind==='ad'?'📢 ':m.mediaKind==='jingle'?'🔊 ':'🎵 ')+(m.title||'Radio Audio');$('#rrSub').textContent=m.mediaKind==='track'?(m.artist||stations[station].name):m.mediaKind==='ad'?(m.text||'Advertisement'):(m.kind==='breaking'?'Breaking-news sting':stations[station].name)}
function playMedia(m){const src=audioSrc(m);if(!src)return false;autoMode=true;showMedia(m);audio.src=new URL(src,location.href).href;audio.volume=Number($('#rrVol')?.value||.8);audio.play().then(()=>{playing=true;renderPlay()}).catch(()=>setStatus('Tap Play again to allow audio.'));return true}
function playNextRotation(){const m=nextRotationItem();if(!m){playing=false;renderPlay();setStatus('No playable audio is attached to this station yet.');return}playMedia(m)}
function playNow(){const n=current();if(n.live)return listenLive();const src=audioSrc(n);if(src){autoMode=false;audio.src=new URL(src,location.href).href;audio.volume=Number($('#rrVol')?.value||.8);audio.play().then(()=>{playing=true;renderPlay()}).catch(()=>setStatus('Tap Play again to allow audio.'));return}playNextRotation()}
function toggle(){if(state?.live?.active&&state.live.station===station&&liveAudio.srcObject)return liveAudio.paused?listenLive():pauseLive();if(playing){audio.pause();playing=false;autoMode=false;renderPlay()}else playNow()}
function renderPlay(){const b=$('#rrPlay');if(b)b.textContent=(state?.live?.active&&state.live.station===station&&liveAudio.srcObject&&!liveAudio.paused)||playing?'⏸ Pause':'▶ Play'}
audio.onended=()=>{playing=false;renderPlay();if(autoMode)playNextRotation()};audio.onerror=()=>{playing=false;renderPlay();setStatus('That audio could not be played. Skipping…');if(autoMode)setTimeout(playNextRotation,500)};
function buy(id){const p=stations[id].price;if(wallet()<p)return alert(`You need ${p} MB. Balance: ${wallet()} MB.`);if(!confirm(`Unlock ${stations[id].name} for ${p} MB?`))return;setWallet(wallet()-p);const o=owned();o[id]={at:new Date().toISOString(),price:p};saveOwned(o);station=id;localStorage.setItem('lizzyRadioStation',id);rotation={first:true,tracksSinceAd:0,lastId:''};render();ensureLive()}
function setStation(id){if(!has(id))return buy(id);if(station!==id){audio.pause();playing=false;autoMode=false;closeLive(false);rotation={first:true,tracksSinceAd:0,lastId:''}}station=id;localStorage.setItem('lizzyRadioStation',id);render();ensureLive()}
function scheduleHtml(){return (state?.schedule||[]).filter(x=>!x.station||x.station===station).slice().sort((a,b)=>minutes(a.time)-minutes(b.time)).map(x=>`<div class="rrItem"><b>${esc(x.time||'')}</b> — ${esc(x.title||'')}</div>`).join('')||'<div class="rrItem">No scheduled shows yet.</div>'}
function archiveHtml(){return (state?.archive||[]).filter(x=>x.station===station).slice(-12).reverse().map(x=>{const src=audioSrc(x);return `<div class="rrItem"><b>${x.type==='live'?'🔴 ':''}${esc(x.title||'Broadcast')}</b><small>${esc(x.text||'')}</small>${src?`<button class="rrSmall" data-audio="${esc(src)}">▶ Replay</button>`:''}</div>`}).join('')||'<div class="rrItem">No broadcasts archived yet.</div>'}
function liveBanner(){const l=state?.live;if(!l?.active)return'';if(l.station!==station)return `<div class="rrItem rrLiveNotice"><b>🔴 HQ is LIVE on ${esc(stations[l.station]?.name||l.station)}</b><small>Switch stations to listen.</small></div>`;return `<div class="rrItem rrLiveNow"><b>🔴 LIVE FROM HQ</b><p>${esc(l.headline||'Breaking broadcast')}</p><button class="rrAction" id="rrListenLive">🎙 Listen Live</button></div>`}
function render(){if(!$('#lzRadioMini'))return;document.querySelectorAll('[data-st]').forEach(b=>{const id=b.dataset.st,unlocked=has(id);b.classList.toggle('on',id===station);b.classList.toggle('locked',!unlocked);b.innerHTML=`<span class="rrStationName">${esc(stations[id].name)}</span>${unlocked?'':`<span class="rrStationPrice">🔒 ${stations[id].price} MB</span>`}`});const n=current();$('#rrTitle').textContent=n.title||stations[station].name;$('#rrSub').textContent=n.subtitle||n.text||'';$('#rrSchedule').innerHTML=scheduleHtml();$('#rrArchive').innerHTML=archiveHtml();$('#rrChallenge').innerHTML=challengeHtml();$('#rrHijackBox').innerHTML=liveBanner()+(state?.hijack?.active?`<div class="rrItem rrHijack"><b>🚨 AIRWAVES HIJACKED</b><p>${esc(state.hijack.text||'Voice takeover in progress')}</p>${state.hijack.audio?`<audio controls src="${esc(state.hijack.audio)}"></audio>`:''}</div>`:'');document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>{const src=b.dataset.audio;audio.src=new URL(src,location.href).href;autoMode=false;audio.play();playing=true;renderPlay()});if($('#rrListenLive'))$('#rrListenLive').onclick=listenLive;renderPlay()}
function challengeHtml(){const c=state?.challenge;if(!c||c.station!=='lizzy')return '<div class="rrItem">No Lizzy Radio challenge live right now.</div>';return `<div class="rrItem"><b>🏆 ${esc(c.title)}</b><p>${esc(c.instruction)}</p><strong>Prize: ${Number(c.prize||0)} MB</strong><p>Auto-confirm: include <b>#LizzyRadio</b> in your message to Mikael.</p><small>${c.completedAt?'✅ Confirmed automatically':'⏳ Waiting for hashtag confirmation'}</small></div>`}
function checkRewards(){const c=state?.challenge;if(!c?.completedAt||!c.id)return;let x={};try{x=JSON.parse(localStorage.getItem(CLAIMED)||'{}')}catch{}if(x[c.id])return;setWallet(wallet()+Number(c.prize||0));x[c.id]=Date.now();localStorage.setItem(CLAIMED,JSON.stringify(x));alert(`🏆 Lizzy Radio challenge confirmed automatically! +${c.prize||0} MB`)}
function waitIce(pc,ms=6500){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const done=()=>{pc.removeEventListener('icegatheringstatechange',on);clearTimeout(t);resolve()};const on=()=>pc.iceGatheringState==='complete'&&done();pc.addEventListener('icegatheringstatechange',on);const t=setTimeout(done,ms)})}
async function ensureLive(){const l=state?.live;if(!l?.active||l.station!==station||!has(station)){if(livePc)closeLive(true);return}if(liveSession===l.id&&livePc)return;if(liveConnecting)return;liveConnecting=true;try{closeLive(false);liveSession=l.id;livePc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});livePc.ontrack=e=>{liveAudio.srcObject=e.streams[0];resumeAfterLive=playing;if(playing){audio.pause();playing=false;autoMode=false}liveAudio.volume=Number($('#rrVol')?.value||.8);liveAudio.play().then(()=>{setStatus('🔴 LIVE from HQ · connected');renderPlay()}).catch(()=>setStatus('🔴 HQ is live. Tap “Listen Live” to hear it.'))};livePc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(livePc?.connectionState))setStatus('Live connection interrupted. Waiting for HQ…')};await livePc.setRemoteDescription({type:'offer',sdp:l.offer});const ans=await livePc.createAnswer();await livePc.setLocalDescription(ans);await waitIce(livePc);await api({type:'radio_live_answer',session:l.id,answer:livePc.localDescription.sdp});setStatus('🔴 Connecting live audio…')}catch(e){setStatus('Could not connect to HQ live audio: '+e.message);closeLive(false)}finally{liveConnecting=false}}
function listenLive(){if(!state?.live?.active||state.live.station!==station)return ensureLive();if(liveAudio.srcObject)liveAudio.play().then(()=>renderPlay()).catch(e=>setStatus('Tap again to allow live audio: '+e.message));else ensureLive()}
function pauseLive(){liveAudio.pause();renderPlay()}
function closeLive(resume){try{livePc?.close()}catch{}livePc=null;liveSession='';liveAudio.pause();liveAudio.srcObject=null;if(resume&&resumeAfterLive){resumeAfterLive=false;playNextRotation()}renderPlay()}
function openModal(kind){$('#rrModal').classList.add('open');$('#rrModalBody').innerHTML=kind==='song'?`<h2>🎵 Request / Suggest a Song</h2><input id="rrSong" placeholder="Song"><input id="rrArtist" placeholder="Artist"><textarea id="rrNote" placeholder="Optional dedication or note"></textarea><div class="rrVoiceRow"><button class="rrAction" id="rrRec">🎙 Record voice request</button><span id="rrRecState"></span><audio id="rrVoicePreview" controls style="display:none"></audio></div><button class="rrAction" id="rrSendReq">Send to HQ</button>`:`<h2>🚨 Hijack Presidential Radio — 1,500 MB</h2><textarea id="rrHijackText" maxlength="120" placeholder="Your 120-character takeover message"></textarea><div class="rrVoiceRow"><button class="rrAction" id="rrRec">🎙 Record hijack audio</button><span id="rrRecState"></span><audio id="rrVoicePreview" controls style="display:none"></audio></div><button class="rrAction rrDanger" id="rrSendReq">Seize the airwaves</button>`;voiceData='';$('#rrRec').onclick=startVoice;$('#rrSendReq').onclick=()=>kind==='song'?sendSong():sendHijack()}
async function startVoice(){if(recorder?.state==='recording'){recorder.stop();return}try{const s=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(s,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{s.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:recorder.mimeType});if(blob.size>2*1024*1024){alert('Voice note is too large. Keep it under about 2 MB.');return}const fr=new FileReader();fr.onload=()=>{voiceData=String(fr.result||'');const p=$('#rrVoicePreview');p.src=voiceData;p.style.display='block';$('#rrRecState').textContent='Voice attached ✓'};fr.readAsDataURL(blob)};recorder.start();$('#rrRec').textContent='⏹ Stop recording';$('#rrRecState').textContent='Recording…';setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},60000)}catch(e){alert('Microphone unavailable: '+e.message)}}
async function sendSong(){try{await api({type:'radio_song_request',song:$('#rrSong').value.trim(),artist:$('#rrArtist').value.trim(),note:$('#rrNote').value.trim(),audio:voiceData});$('#rrModal').classList.remove('open');setStatus('Song request sent to HQ ✓')}catch(e){alert(e.message)}}
async function sendHijack(){if(wallet()<1500)return alert('Hijacking costs 1,500 MB.');const text=$('#rrHijackText').value.trim();if(!text&&!voiceData)return alert('Add a message or voice note.');try{await api({type:'radio_hijack',station:'presidential',text,audio:voiceData});setWallet(wallet()-1500);$('#rrModal').classList.remove('open');setStatus('Airwaves seized. HQ has been alerted.');pull()}catch(e){alert(e.message)}}
function mount(){document.body.insertAdjacentHTML('beforeend',`<div id="lzRadioDock"><button id="lzRadioBtn">📻 Radio</button><div id="lzRadioMini"><div class="rrHead"><div><span class="rrLiveDot"></span><b>LizzyOS Radio</b></div><button class="rrSmall" id="rrClose">—</button></div><div class="rrTabs"><button data-st="propaganda"></button><button data-st="lizzy"></button><button data-st="presidential"></button></div><div class="rrBody"><div id="rrHijackBox"></div><div class="rrNow"><small>NOW PLAYING</small><b id="rrTitle"></b><p id="rrSub"></p><div class="rrWave"></div><div class="rrControls"><button class="rrAction" id="rrPlay">▶ Play</button><label>🔊 <input id="rrVol" type="range" min="0" max="1" step=".05" value=".8"></label></div><div id="rrStatus" class="rrStatus">Connecting to TEST Worker…</div></div><div class="rrGrid"><button class="rrAction" data-pane="schedule">🗓 Schedule</button><button class="rrAction" data-pane="challenge">🏆 Challenge</button><button class="rrAction" id="rrSongReq">🎵 Request Song</button><button class="rrAction" id="rrHijack">🚨 Hijack</button><button class="rrAction" data-pane="archive">🗃 Archive</button><button class="rrAction" id="rrRefresh">↻ Refresh</button></div><div id="rrSchedule" class="rrPanel"></div><div id="rrChallenge" class="rrPanel"></div><div id="rrArchive" class="rrPanel"></div></div></div></div><div id="rrModal" class="rrModal"><div class="rrCard"><button class="rrSmall" id="rrModalClose">✕</button><div id="rrModalBody"></div></div></div>`);$('#lzRadioBtn').onclick=()=>$('#lzRadioMini').classList.toggle('open');$('#rrClose').onclick=()=>$('#lzRadioMini').classList.remove('open');$('#rrModalClose').onclick=()=>$('#rrModal').classList.remove('open');document.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>setStation(b.dataset.st));document.querySelectorAll('[data-pane]').forEach(b=>b.onclick=()=>{const p=$('#rr'+b.dataset.pane[0].toUpperCase()+b.dataset.pane.slice(1));p.classList.toggle('on')});$('#rrPlay').onclick=toggle;$('#rrVol').oninput=e=>{audio.volume=Number(e.target.value);liveAudio.volume=Number(e.target.value)};$('#rrSongReq').onclick=()=>{if(!has('lizzy'))return buy('lizzy');openModal('song')};$('#rrHijack').onclick=()=>{if(!has('presidential'))return buy('presidential');openModal('hijack')};$('#rrRefresh').onclick=pull;render();pull();setInterval(pull,6000)}
window.addEventListener('beforeunload',()=>closeLive(false));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
